#ifndef GUARD_CONSTANTS_OPPONENTS_JOHTO_H
#define GUARD_CONSTANTS_OPPONENTS_JOHTO_H

#define TRAINER_BEAUTY_OLIVIA                            861
#define TRAINER_BEAUTY_SAMANTHA                          862
#define TRAINER_BEAUTY_VALERIE                           863
#define TRAINER_BEAUTY_VICTORIA                          864
#define TRAINER_BIRD_KEEPER_ABE                          865
#define TRAINER_BIRD_KEEPER_BRYAN                        866
#define TRAINER_BIRD_KEEPER_DENIS                        867
#define TRAINER_BIRD_KEEPER_JOSE1                        868
#define TRAINER_BIRD_KEEPER_JOSE2                        869
#define TRAINER_BIRD_KEEPER_JOSE3                        870
#define TRAINER_BIRD_KEEPER_PETER                        871
#define TRAINER_BIRD_KEEPER_ROD                          872
#define TRAINER_BIRD_KEEPER_THEO                         873
#define TRAINER_BIRD_KEEPER_TOBY                         874
#define TRAINER_BIRD_KEEPER_VANCE1                       875
#define TRAINER_BIRD_KEEPER_VANCE2                       876
#define TRAINER_BIRD_KEEPER_VANCE3                       877
#define TRAINER_BLACKBELT_T_KENJI3                       878
#define TRAINER_BLACKBELT_T_KIYO                         879
#define TRAINER_BLACKBELT_T_LAO                          880
#define TRAINER_BLACKBELT_T_LUNG                         881
#define TRAINER_BLACKBELT_T_NOB                          882
#define TRAINER_BLACKBELT_T_YOSHI                        883
#define TRAINER_BOARDER_BRAD                             884
#define TRAINER_BOARDER_DOUGLAS                          885
#define TRAINER_BOARDER_RONALD                           886
#define TRAINER_BRUNO_BRUNO1                             887
#define TRAINER_BUGSY_BUGSY1                             888
#define TRAINER_BUG_CATCHER_AL                           889
#define TRAINER_BUG_CATCHER_ARNIE1                       890
#define TRAINER_BUG_CATCHER_ARNIE2                       891
#define TRAINER_BUG_CATCHER_ARNIE3                       892
#define TRAINER_BUG_CATCHER_ARNIE4                       893
#define TRAINER_BUG_CATCHER_ARNIE5                       894
#define TRAINER_BUG_CATCHER_BUG_CATCHER_BENNY            895
#define TRAINER_BUG_CATCHER_JOSH                         896
#define TRAINER_BUG_CATCHER_WADE1                        897
#define TRAINER_BUG_CATCHER_WADE2                        898
#define TRAINER_BUG_CATCHER_WADE3                        899
#define TRAINER_BUG_CATCHER_WADE4                        900
#define TRAINER_BUG_CATCHER_WADE5                        901
#define TRAINER_BUG_CATCHER_WAYNE                        902
#define TRAINER_BURGLAR_DUNCAN                           903
#define TRAINER_BURGLAR_EDDIE                            904
#define TRAINER_CAMPER_ELLIOT                            905
#define TRAINER_CAMPER_IVAN                              906
#define TRAINER_CAMPER_QUENTIN                           907
#define TRAINER_CAMPER_ROLAND                            908
#define TRAINER_CAMPER_SPENCER                           909
#define TRAINER_CAMPER_TED                               910
#define TRAINER_CAMPER_TODD1                             911
#define TRAINER_CAMPER_TODD2                             912
#define TRAINER_CAMPER_TODD3                             913
#define TRAINER_CAMPER_TODD4                             914
#define TRAINER_CAMPER_TODD5                             915
#define TRAINER_CHAMPION_LANCE                           916
#define TRAINER_CHUCK_CHUCK1                             917
#define TRAINER_CLAIR_CLAIR1                             918
#define TRAINER_COOLTRAINERF_BETH1                       919
#define TRAINER_COOLTRAINERF_BETH2                       920
#define TRAINER_COOLTRAINERF_BETH3                       921
#define TRAINER_COOLTRAINERF_CARA                        922
#define TRAINER_COOLTRAINERF_CYBIL                       923
#define TRAINER_COOLTRAINERF_EMMA                        924
#define TRAINER_COOLTRAINERF_FRAN                        925
#define TRAINER_COOLTRAINERF_GWEN                        926
#define TRAINER_COOLTRAINERF_IRENE                       927
#define TRAINER_COOLTRAINERF_JENN                        928
#define TRAINER_COOLTRAINERF_JOYCE                       929
#define TRAINER_COOLTRAINERF_KATE                        930
#define TRAINER_COOLTRAINERF_KELLY                       931
#define TRAINER_COOLTRAINERF_LOIS                        932
#define TRAINER_COOLTRAINERF_LOLA                        933
#define TRAINER_COOLTRAINERF_MEGAN                       934
#define TRAINER_COOLTRAINERF_REENA1                      935
#define TRAINER_COOLTRAINERF_REENA2                      936
#define TRAINER_COOLTRAINERF_REENA3                      937
#define TRAINER_COOLTRAINERM_AARON                       938
#define TRAINER_COOLTRAINERM_ALLEN                       939
#define TRAINER_COOLTRAINERM_BLAKE                       940
#define TRAINER_COOLTRAINERM_BRIAN                       941
#define TRAINER_COOLTRAINERM_CODY                        942
#define TRAINER_COOLTRAINERM_DARIN                       943
#define TRAINER_COOLTRAINERM_GAVEN1                      944
#define TRAINER_COOLTRAINERM_GAVEN2                      945
#define TRAINER_COOLTRAINERM_GAVEN3                      946
#define TRAINER_COOLTRAINERM_JAKE                        947
#define TRAINER_COOLTRAINERM_MIKE                        948
#define TRAINER_COOLTRAINERM_NICK                        949
#define TRAINER_COOLTRAINERM_PAUL                        950
#define TRAINER_COOLTRAINERM_RYAN                        951
#define TRAINER_EXECUTIVEF_EXECUTIVEF_1                  952
#define TRAINER_EXECUTIVEF_EXECUTIVEF_2                  953
#define TRAINER_EXECUTIVEM_EXECUTIVEM_1                  954
#define TRAINER_EXECUTIVEM_EXECUTIVEM_2                  955
#define TRAINER_EXECUTIVEM_EXECUTIVEM_3                  956
#define TRAINER_EXECUTIVEM_EXECUTIVEM_4                  957
#define TRAINER_FALKNER_FALKNER1                         958
#define TRAINER_FIREBREATHER_BILL                        959
#define TRAINER_FIREBREATHER_RAY                         960
#define TRAINER_FIREBREATHER_WALT                        961
#define TRAINER_FISHER_ANDRE                             962
#define TRAINER_FISHER_EDGAR                             963
#define TRAINER_FISHER_HENRY                             964
#define TRAINER_FISHER_JUSTIN                            965
#define TRAINER_FISHER_MARVIN                            966
#define TRAINER_FISHER_RALPH1                            967
#define TRAINER_FISHER_RALPH2                            968
#define TRAINER_FISHER_RALPH3                            969
#define TRAINER_FISHER_RALPH4                            970
#define TRAINER_FISHER_RALPH5                            971
#define TRAINER_FISHER_RAYMOND                           972
#define TRAINER_FISHER_SCOTT                             973
#define TRAINER_FISHER_TULLY1                            974
#define TRAINER_FISHER_TULLY2                            975
#define TRAINER_FISHER_TULLY3                            976
#define TRAINER_FISHER_TULLY4                            977
#define TRAINER_FISHER_WILTON1                           978
#define TRAINER_FISHER_WILTON2                           979
#define TRAINER_FISHER_WILTON3                           980
#define TRAINER_GENTLEMAN_ALFRED                         981
#define TRAINER_GENTLEMAN_PRESTON                        982
#define TRAINER_GRUNTF_GRUNTF_1                          983
#define TRAINER_GRUNTF_GRUNTF_2                          984
#define TRAINER_GRUNTF_GRUNTF_3                          985
#define TRAINER_GRUNTF_GRUNTF_4                          986
#define TRAINER_GRUNTF_GRUNTF_5                          987
#define TRAINER_GRUNTM_GRUNTM_1                          988
#define TRAINER_GRUNTM_GRUNTM_10                         989
#define TRAINER_GRUNTM_GRUNTM_11                         990
#define TRAINER_GRUNTM_GRUNTM_13                         991
#define TRAINER_GRUNTM_GRUNTM_14                         992
#define TRAINER_GRUNTM_GRUNTM_15                         993
#define TRAINER_GRUNTM_GRUNTM_16                         994
#define TRAINER_GRUNTM_GRUNTM_17                         995
#define TRAINER_GRUNTM_GRUNTM_18                         996
#define TRAINER_GRUNTM_GRUNTM_19                         997
#define TRAINER_GRUNTM_GRUNTM_2                          998
#define TRAINER_GRUNTM_GRUNTM_20                         999
#define TRAINER_GRUNTM_GRUNTM_21                         1000
#define TRAINER_GRUNTM_GRUNTM_24                         1001
#define TRAINER_GRUNTM_GRUNTM_25                         1002
#define TRAINER_GRUNTM_GRUNTM_28                         1003
#define TRAINER_GRUNTM_GRUNTM_29                         1004
#define TRAINER_GRUNTM_GRUNTM_3                          1005
#define TRAINER_GRUNTM_GRUNTM_4                          1006
#define TRAINER_GRUNTM_GRUNTM_5                          1007
#define TRAINER_GRUNTM_GRUNTM_6                          1008
#define TRAINER_GRUNTM_GRUNTM_7                          1009
#define TRAINER_GRUNTM_GRUNTM_8                          1010
#define TRAINER_GRUNTM_GRUNTM_9                          1011
#define TRAINER_HIKER_ANTHONY1                           1012
#define TRAINER_HIKER_ANTHONY2                           1013
#define TRAINER_HIKER_ANTHONY3                           1014
#define TRAINER_HIKER_ANTHONY4                           1015
#define TRAINER_HIKER_ANTHONY5                           1016
#define TRAINER_HIKER_BAILEY                             1017
#define TRAINER_HIKER_BENJAMIN                           1018
#define TRAINER_HIKER_DANIEL                             1019
#define TRAINER_HIKER_ERIK                               1020
#define TRAINER_HIKER_LEONARD                            1021
#define TRAINER_HIKER_MICHAEL                            1022
#define TRAINER_HIKER_PARRY1                             1023
#define TRAINER_HIKER_PARRY2                             1024
#define TRAINER_HIKER_PARRY3                             1025
#define TRAINER_HIKER_PHILLIP                            1026
#define TRAINER_HIKER_RUSSELL                            1027
#define TRAINER_HIKER_TIMOTHY                            1028
#define TRAINER_JASMINE_JASMINE1                         1029
#define TRAINER_JUGGLER_IRWIN1                           1030
#define TRAINER_KAREN_KAREN1                             1031
#define TRAINER_KIMONO_GIRL_KUNI                         1032
#define TRAINER_KIMONO_GIRL_MIKI                         1033
#define TRAINER_KIMONO_GIRL_NAOKO                        1034
#define TRAINER_KIMONO_GIRL_SAYO                         1035
#define TRAINER_KIMONO_GIRL_ZUKI                         1036
#define TRAINER_KOGA_KOGA1                               1037
#define TRAINER_LASS_BRIDGET                             1038
#define TRAINER_LASS_CARRIE                              1039
#define TRAINER_LASS_CONNIE1                             1040
#define TRAINER_LASS_DANA1                               1041
#define TRAINER_LASS_DANA2                               1042
#define TRAINER_LASS_DANA3                               1043
#define TRAINER_LASS_DANA4                               1044
#define TRAINER_LASS_DANA5                               1045
#define TRAINER_LASS_KRISE                               1046
#define TRAINER_MEDIUM_GRACE                             1047
#define TRAINER_MEDIUM_MARTHA                            1048
#define TRAINER_MORTY_MORTY1                             1049
#define TRAINER_MYSTICALMAN_EUSINE                       1050
#define TRAINER_OFFICER_DIRK                             1051
#define TRAINER_OFFICER_KEITH                            1052
#define TRAINER_PICNICKER_BROOKE                         1053
#define TRAINER_PICNICKER_ERIN1                          1054
#define TRAINER_PICNICKER_ERIN2                          1055
#define TRAINER_PICNICKER_ERIN3                          1056
#define TRAINER_PICNICKER_GINA1                          1057
#define TRAINER_PICNICKER_GINA2                          1058
#define TRAINER_PICNICKER_GINA3                          1059
#define TRAINER_PICNICKER_GINA4                          1060
#define TRAINER_PICNICKER_GINA5                          1061
#define TRAINER_PICNICKER_KIM                            1062
#define TRAINER_PICNICKER_LIZ1                           1063
#define TRAINER_PICNICKER_LIZ2                           1064
#define TRAINER_PICNICKER_LIZ3                           1065
#define TRAINER_PICNICKER_LIZ4                           1066
#define TRAINER_PICNICKER_LIZ5                           1067
#define TRAINER_PICNICKER_TIFFANY1                       1068
#define TRAINER_PICNICKER_TIFFANY2                       1069
#define TRAINER_PICNICKER_TIFFANY3                       1070
#define TRAINER_PICNICKER_TIFFANY4                       1071
#define TRAINER_POKEFANF_BEVERLY1                        1072
#define TRAINER_POKEFANF_JAIME                           1073
#define TRAINER_POKEFANF_RUTH                            1074
#define TRAINER_POKEFANM_BRANDON                         1075
#define TRAINER_POKEFANM_DEREK1                          1076
#define TRAINER_POKEFANM_WILLIAM                         1077
#define TRAINER_POKEMANIAC_ANDREW                        1078
#define TRAINER_POKEMANIAC_BEN                           1079
#define TRAINER_POKEMANIAC_BRENT1                        1080
#define TRAINER_POKEMANIAC_BRENT2                        1081
#define TRAINER_POKEMANIAC_BRENT3                        1082
#define TRAINER_POKEMANIAC_BRENT4                        1083
#define TRAINER_POKEMANIAC_CALVIN                        1084
#define TRAINER_POKEMANIAC_DONALD                        1085
#define TRAINER_POKEMANIAC_ISSAC                         1086
#define TRAINER_POKEMANIAC_LARRY                         1087
#define TRAINER_POKEMANIAC_MILLER                        1088
#define TRAINER_POKEMANIAC_RON                           1089
#define TRAINER_POKEMANIAC_SHANE                         1090
#define TRAINER_POKEMANIAC_ZACH                          1091
#define TRAINER_PRYCE_PRYCE1                             1092
#define TRAINER_PSYCHIC_T_GILBERT                        1093
#define TRAINER_PSYCHIC_T_GREG                           1094
#define TRAINER_PSYCHIC_T_MARK                           1095
#define TRAINER_PSYCHIC_T_NATHAN                         1096
#define TRAINER_PSYCHIC_T_NORMAN                         1097
#define TRAINER_PSYCHIC_T_PHIL                           1098
#define TRAINER_PSYCHIC_T_RICHARD                        1099
#define TRAINER_RIVAL1_RIVAL1_1_CHIKORITA                1100
#define TRAINER_RIVAL1_RIVAL1_1_CYNDAQUIL                1101
#define TRAINER_RIVAL1_RIVAL1_1_TOTODILE                 1102
#define TRAINER_RIVAL1_RIVAL1_2_CHIKORITA                1103
#define TRAINER_RIVAL1_RIVAL1_2_CYNDAQUIL                1104
#define TRAINER_RIVAL1_RIVAL1_2_TOTODILE                 1105
#define TRAINER_RIVAL1_RIVAL1_3_CHIKORITA                1106
#define TRAINER_RIVAL1_RIVAL1_3_CYNDAQUIL                1107
#define TRAINER_RIVAL1_RIVAL1_3_TOTODILE                 1108
#define TRAINER_RIVAL1_RIVAL1_4_CHIKORITA                1109
#define TRAINER_RIVAL1_RIVAL1_4_CYNDAQUIL                1110
#define TRAINER_RIVAL1_RIVAL1_4_TOTODILE                 1111
#define TRAINER_RIVAL1_RIVAL1_5_CHIKORITA                1112
#define TRAINER_RIVAL1_RIVAL1_5_CYNDAQUIL                1113
#define TRAINER_RIVAL1_RIVAL1_5_TOTODILE                 1114
#define TRAINER_RIVAL2_RIVAL2_2_CHIKORITA                1115
#define TRAINER_RIVAL2_RIVAL2_2_CYNDAQUIL                1116
#define TRAINER_RIVAL2_RIVAL2_2_TOTODILE                 1117
#define TRAINER_SAGE_CHOW                                1118
#define TRAINER_SAGE_EDMOND                              1119
#define TRAINER_SAGE_GAKU                                1120
#define TRAINER_SAGE_JEFFREY                             1121
#define TRAINER_SAGE_JIN                                 1122
#define TRAINER_SAGE_KOJI                                1123
#define TRAINER_SAGE_LI                                  1124
#define TRAINER_SAGE_MASA                                1125
#define TRAINER_SAGE_NEAL                                1126
#define TRAINER_SAGE_NICO                                1127
#define TRAINER_SAGE_PING                                1128
#define TRAINER_SAGE_TROY                                1129
#define TRAINER_SAILOR_ERNEST                            1130
#define TRAINER_SAILOR_EUGENE                            1131
#define TRAINER_SAILOR_HARRY                             1132
#define TRAINER_SAILOR_HUEY1                             1133
#define TRAINER_SAILOR_HUEY2                             1134
#define TRAINER_SAILOR_HUEY3                             1135
#define TRAINER_SAILOR_HUEY4                             1136
#define TRAINER_SAILOR_KENT                              1137
#define TRAINER_SAILOR_TERRELL                           1138
#define TRAINER_SCHOOLBOY_ALAN1                          1139
#define TRAINER_SCHOOLBOY_ALAN2                          1140
#define TRAINER_SCHOOLBOY_ALAN3                          1141
#define TRAINER_SCHOOLBOY_ALAN4                          1142
#define TRAINER_SCHOOLBOY_ALAN5                          1143
#define TRAINER_SCHOOLBOY_CHAD1                          1144
#define TRAINER_SCHOOLBOY_CHAD2                          1145
#define TRAINER_SCHOOLBOY_CHAD3                          1146
#define TRAINER_SCHOOLBOY_CHAD4                          1147
#define TRAINER_SCHOOLBOY_CHAD5                          1148
#define TRAINER_SCHOOLBOY_JACK1                          1149
#define TRAINER_SCHOOLBOY_JACK2                          1150
#define TRAINER_SCHOOLBOY_JACK3                          1151
#define TRAINER_SCHOOLBOY_JACK4                          1152
#define TRAINER_SCHOOLBOY_JACK5                          1153
#define TRAINER_SCIENTIST_JED                            1154
#define TRAINER_SCIENTIST_MARC                           1155
#define TRAINER_SCIENTIST_MITCH                          1156
#define TRAINER_SCIENTIST_RICH                           1157
#define TRAINER_SCIENTIST_ROSS                           1158
#define TRAINER_SKIER_CLARISSA                           1159
#define TRAINER_SKIER_ROXANNE                            1160
#define TRAINER_SUPER_NERD_ERIC                          1161
#define TRAINER_SUPER_NERD_HUGH                          1162
#define TRAINER_SUPER_NERD_MARKUS                        1163
#define TRAINER_SUPER_NERD_STAN                          1164
#define TRAINER_SUPER_NERD_TERU                          1165
#define TRAINER_SWIMMERF_DENISE                          1166
#define TRAINER_SWIMMERF_ELAINE                          1167
#define TRAINER_SWIMMERF_KARA                            1168
#define TRAINER_SWIMMERF_KAYLEE                          1169
#define TRAINER_SWIMMERF_PAULA                           1170
#define TRAINER_SWIMMERF_SUSIE                           1171
#define TRAINER_SWIMMERF_WENDY                           1172
#define TRAINER_SWIMMERM_BERKE                           1173
#define TRAINER_SWIMMERM_CHARLIE                         1174
#define TRAINER_SWIMMERM_GEORGE                          1175
#define TRAINER_SWIMMERM_KIRK                            1176
#define TRAINER_SWIMMERM_MATHEW                          1177
#define TRAINER_SWIMMERM_RANDALL                         1178
#define TRAINER_SWIMMERM_SIMON                           1179
#define TRAINER_TWINS_AMYANDMAY1                         1180
#define TRAINER_TWINS_AMYANDMAY2                         1181
#define TRAINER_TWINS_ANNANDANNE1                        1182
#define TRAINER_TWINS_ANNANDANNE2                        1183
#define TRAINER_TWINS_LEAANDPIA1                         1184
#define TRAINER_WHITNEY_WHITNEY1                         1185
#define TRAINER_WILL_WILL1                               1186
#define TRAINER_YOUNGSTER_ALBERT                         1187
#define TRAINER_YOUNGSTER_GORDON                         1188
#define TRAINER_YOUNGSTER_IAN                            1189
#define TRAINER_YOUNGSTER_JOEY2                          1190
#define TRAINER_YOUNGSTER_JOEY3                          1191
#define TRAINER_YOUNGSTER_JOEY4                          1192
#define TRAINER_YOUNGSTER_JOEY5                          1193
#define TRAINER_YOUNGSTER_SAMUEL                         1194

#define TRAINER_JOHTO_LAST 1194
#endif  // GUARD_CONSTANTS_OPPONENTS_JOHTO_H
