gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is ELM.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "Every town, route, and forest has its\n"
	.string "own stories to tell about them.\p"
	.string "I've been studying how POKéMON live,\n"
	.string "grow, and change across JOHTO.\p"
	.string "There are still so many mysteries to\n"
	.string "unravel, and that's what drives my\l"
	.string "research every day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} from NEW BARK\n"
	.string "TOWN.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll be waiting for you in NEW BARK\n"
	.string "TOWN's POKéMON LAB.\p"
	.string "$"
