#!/usr/bin/env python3

import argparse
import re
import struct
import sys
from typing import Optional

from generate_johto_trainers import trainer_constant_name
from johto_import_common import (
    AUTO_JOHTO_SCRIPTS_PATH,
    CRYSTAL_ROOT,
    HEAL_LOCATIONS_PATH,
    IR_DIR,
    LAYOUTS_PATH,
    MAP_GROUPS_PATH,
    REGION_MAP_SECTIONS_PATH,
    ROOT,
    CRYSTAL_LANDMARKS,
    block_bytes_for_ir,
    crystal_connection_offset_to_emerald,
    extract_crystal_ir,
    load_crystal_tilesets,
    load_import_manifest,
    load_json,
    load_target_map,
    load_target_map_index,
    save_json,
)


CRYSTAL_TO_EMERALD_DIRECTION = {
    "north": "up",
    "south": "down",
    "west": "left",
    "east": "right",
}

CRYSTAL_BG_KIND_TO_FACING = {
    "BGEVENT_READ": "BG_EVENT_PLAYER_FACING_ANY",
    "BGEVENT_UP": "BG_EVENT_PLAYER_FACING_NORTH",
    "BGEVENT_DOWN": "BG_EVENT_PLAYER_FACING_SOUTH",
    "BGEVENT_LEFT": "BG_EVENT_PLAYER_FACING_WEST",
    "BGEVENT_RIGHT": "BG_EVENT_PLAYER_FACING_EAST",
    "BGEVENT_IFSET": "BG_EVENT_PLAYER_FACING_ANY",
    "BGEVENT_IFNOTSET": "BG_EVENT_PLAYER_FACING_ANY",
}

GENERATED_JOHTO_ASSETS_PATH = ROOT / "data" / "maps" / "johto_generated_assets.inc"
AUTO_SCRIPT_HEADER = "@ Generated by scripts/import_johto_maps.py. Replace manually if needed."
CRYSTAL_MART_CONSTANTS_PATH = CRYSTAL_ROOT / "constants" / "mart_constants.asm"
CRYSTAL_MARTS_PATH = CRYSTAL_ROOT / "data" / "items" / "marts.asm"

TEXT_SUBSTITUTIONS = (
    ("#MON\\pGEAR", "POKENAV"),
    ("#MON\\nGEAR", "POKENAV"),
    ("#MON GEAR", "POKENAV"),
    ("<PLAY_G>", "{PLAYER}"),
    ("<PLAYER>", "{PLAYER}"),
    ("#MON", "POKéMON"),
    ("#GEAR", "POKENAV"),
    ("POKéGEAR", "POKENAV"),
    ("MAP CARD", "JOHTO MAP"),
)

TEXT_RAM_PLACEHOLDERS = {
    "wStringBuffer1": "{STR_VAR_1}",
    "wStringBuffer2": "{STR_VAR_2}",
    "wStringBuffer3": "{STR_VAR_3}",
}

CRYSTAL_STRING_BUFFER_ALIASES = {
    "STRING_BUFFER_3": "STR_VAR_1",
    "STRING_BUFFER_4": "STR_VAR_2",
}

DIRECTION_SUFFIX = {
    "UP": "up",
    "DOWN": "down",
    "LEFT": "left",
    "RIGHT": "right",
}

CRYSTAL_SPRITE_GFX = {
    "SPRITE_BUG_CATCHER": "OBJ_EVENT_GFX_BUG_CATCHER",
    "SPRITE_CLERK": "OBJ_EVENT_GFX_MART_EMPLOYEE",
    "SPRITE_CONSOLE": "OBJ_EVENT_GFX_GAMEBOY_KID",
    "SPRITE_COOLTRAINER_F": "OBJ_EVENT_GFX_WOMAN_5",
    "SPRITE_COOLTRAINER_M": "OBJ_EVENT_GFX_MAN_3",
    "SPRITE_DOLL_1": "OBJ_EVENT_GFX_PIKACHU_DOLL",
    "SPRITE_DOLL_2": "OBJ_EVENT_GFX_MARILL_DOLL",
    "SPRITE_BIG_DOLL": "OBJ_EVENT_GFX_BIG_SNORLAX_DOLL",
    "SPRITE_ELM": "OBJ_EVENT_GFX_SCIENTIST_1",
    "SPRITE_FISHER": "OBJ_EVENT_GFX_FISHERMAN",
    "SPRITE_FRUIT_TREE": "OBJ_EVENT_GFX_BERRY_TREE",
    "SPRITE_GENTLEMAN": "OBJ_EVENT_GFX_GENTLEMAN",
    "SPRITE_GRANDFATHER": "OBJ_EVENT_GFX_OLD_MAN",
    "SPRITE_GRANNY": "OBJ_EVENT_GFX_OLD_WOMAN",
    "SPRITE_LASS": "OBJ_EVENT_GFX_LASS",
    "SPRITE_LINK_RECEPTIONIST": "OBJ_EVENT_GFX_LINK_RECEPTIONIST",
    "SPRITE_MOM": "OBJ_EVENT_GFX_MOM",
    "SPRITE_MONSTER": "OBJ_EVENT_GFX_POOCHYENA",
    "SPRITE_NURSE": "OBJ_EVENT_GFX_NURSE",
    "SPRITE_OAK": "OBJ_EVENT_GFX_PROF_BIRCH",
    "SPRITE_OFFICER": "OBJ_EVENT_GFX_MAN_1",
    "SPRITE_POKE_BALL": "OBJ_EVENT_GFX_ITEM_BALL",
    "SPRITE_POKEFAN_F": "OBJ_EVENT_GFX_POKEFAN_F",
    "SPRITE_POKEFAN_M": "OBJ_EVENT_GFX_POKEFAN_M",
    "SPRITE_RIVAL": "OBJ_EVENT_GFX_RED",
    "SPRITE_SCIENTIST": "OBJ_EVENT_GFX_SCIENTIST_2",
    "SPRITE_TEACHER": "OBJ_EVENT_GFX_WOMAN_1",
    "SPRITE_YOUNGSTER": "OBJ_EVENT_GFX_YOUNGSTER",
}

CRYSTAL_MOVEMENT_TYPES = {
    "SPRITEMOVEDATA_BIGDOLL": "MOVEMENT_TYPE_FACE_DOWN",
    "SPRITEMOVEDATA_POKEMON": "MOVEMENT_TYPE_LOOK_AROUND",
    "SPRITEMOVEDATA_SPINCLOCKWISE": "MOVEMENT_TYPE_ROTATE_CLOCKWISE",
    "SPRITEMOVEDATA_SPINCOUNTERCLOCKWISE": "MOVEMENT_TYPE_ROTATE_COUNTERCLOCKWISE",
    "SPRITEMOVEDATA_SPINRANDOM_FAST": "MOVEMENT_TYPE_LOOK_AROUND",
    "SPRITEMOVEDATA_SPINRANDOM_SLOW": "MOVEMENT_TYPE_LOOK_AROUND",
    "SPRITEMOVEDATA_STANDING_DOWN": "MOVEMENT_TYPE_FACE_DOWN",
    "SPRITEMOVEDATA_STANDING_LEFT": "MOVEMENT_TYPE_FACE_LEFT",
    "SPRITEMOVEDATA_STANDING_RIGHT": "MOVEMENT_TYPE_FACE_RIGHT",
    "SPRITEMOVEDATA_STANDING_UP": "MOVEMENT_TYPE_FACE_UP",
    "SPRITEMOVEDATA_STILL": "MOVEMENT_TYPE_LOOK_AROUND",
    "SPRITEMOVEDATA_WALK_LEFT_RIGHT": "MOVEMENT_TYPE_WANDER_LEFT_AND_RIGHT",
    "SPRITEMOVEDATA_WALK_UP_DOWN": "MOVEMENT_TYPE_WANDER_UP_AND_DOWN",
    "SPRITEMOVEDATA_WANDER": "MOVEMENT_TYPE_WANDER_AROUND",
}

SCRIPT_CATEGORY_PRIORITY = {
    "object": 3,
    "coord": 2,
    "bg": 1,
}

PRUNABLE_JOHTO_REGION_SECTIONS = {
    "MAPSEC_BURNED_TOWER",
    "MAPSEC_LIGHTHOUSE",
    "MAPSEC_MT_MORTAR",
    "MAPSEC_TIN_TOWER",
    "MAPSEC_WHIRL_ISLANDS",
}

DECIMAL_TEXT_PLACEHOLDER_RE = re.compile(r"\{d:([A-Z0-9_]+)\}")
LOCAL_TEXT_CONSTANT_RE = re.compile(r"^\s*DEF\s+([A-Z0-9_]+)\s+EQU\s+([0-9]+)\b")
C_DEFINE_RE = re.compile(r"^#define\s+([A-Z0-9_]+)\b")
GLOBAL_TEXT_NUMERIC_CONSTANTS = {
    "BUG_CONTEST_BALLS": "20",
    "BUG_CONTEST_MINUTES": "20",
    "NUM_TMS": "50",
    "NUM_UNOWN": "26",
}
TEXT_NUMERIC_CONSTANTS_CACHE = {}
STANDARD_GOTO_SCRIPTS = {
    "DifficultBookshelfScript": "JohtoCommon_EventScript_DifficultBookshelf",
    "ElevatorButtonScript": "JohtoCommon_EventScript_ElevatorButton",
    "GymStatue1Script": "JohtoCommon_EventScript_GymStatue1",
    "GymStatue2Script": "JohtoCommon_EventScript_GymStatue2",
    "MagazineBookshelfScript": "JohtoCommon_EventScript_MagazineBookshelf",
    "MartSignScript": "Common_EventScript_ShowPokemartSign",
    "PictureBookshelfScript": "JohtoCommon_EventScript_PictureBookshelf",
    "PokecenterSignScript": "Common_EventScript_ShowPokemonCenterSign",
    "Radio1Script": "JohtoCommon_EventScript_Radio1",
    "Radio2Script": "JohtoCommon_EventScript_Radio2",
    "SmashRockScript": "EventScript_SmashRock",
    "StrengthBoulderScript": "EventScript_StrengthBoulder",
    "TeamRocketOathScript": "JohtoCommon_EventScript_TeamRocketOath",
    "TrashCanScript": "JohtoCommon_EventScript_TrashCan",
}
RAW_VALUE_ALIASES = {
    "PARTY_LENGTH": "PARTY_SIZE",
    "GBCHECK_CGB": "1",
    "LAST_TALKED": "VAR_LAST_TALKED",
    "NUM_UNOWN": "26",
    "UP": "DIR_NORTH",
    "DOWN": "DIR_SOUTH",
    "LEFT": "DIR_WEST",
    "RIGHT": "DIR_EAST",
}
RAW_SPECIAL_TRANSLATIONS = {
    "GameboyCheck": ["setvar VAR_RESULT, 1"],
    "HealParty": ["special HealPlayerParty"],
    "RestartMapMusic": ["special Overworld_PlaySpecialMapMusic"],
    "UnlockMysteryGift": ["setflag FLAG_SYS_MYSTERY_GIFT_ENABLE"],
}
RAW_READVAR_TRANSLATIONS = {
    "VAR_PARTYCOUNT": ["special CalculatePlayerPartyCount"],
    "VAR_UNOWNCOUNT": ["special GetJohtoUnownCount"],
    "VAR_WEEKDAY": ["special GetJohtoWeekday"],
}
RAW_MUSIC_ALIASES = {
    "MUSIC_RIVAL_ENCOUNTER": "MUS_RG_ENCOUNTER_RIVAL",
}
RAW_SOUND_ALIASES = {
    "SFX_ELEVATOR": "SE_ELEVATOR",
    "SFX_ELEVATOR_END": "SE_ELEVATOR",
    "SFX_EXIT_BUILDING": "SE_EXIT",
    "SFX_READ_TEXT_2": "SE_SELECT",
    "SFX_TALLY": "SE_PIN",
}
RAW_SPECIES_ALIASES = {
    "SPECIES_FARFETCH_D": "SPECIES_FARFETCHD",
}


def load_define_names(path):
    names = set()
    if not path.exists():
        return names

    for raw_line in path.read_text().splitlines():
        line = raw_line.split("//", 1)[0].strip()
        match = C_DEFINE_RE.match(line)
        if match is not None:
            names.add(match.group(1))
    return names


def load_constant_names_from_dir(directory):
    names = set()
    if not directory.exists():
        return names
    for path in directory.rglob("*.h"):
        names.update(load_define_names(path))
    return names


CONSTANT_NAMES = load_constant_names_from_dir(ROOT / "include" / "constants")
BERRY_TREE_CONSTANTS = {name for name in CONSTANT_NAMES if name.startswith("BERRY_TREE_")}
AVAILABLE_SPECIALS = set(re.findall(r"^\s*def_special\s+(\w+)\s*$", (ROOT / "data" / "specials.inc").read_text(), re.M))
EMERALD_BERRY_SOIL_METATILE_ID = 0x14C
MAPGRID_IMPASSABLE = 0x0400
JOHTO_BERRY_TREES = {
    "FRUITTREE_ROUTE_29": {
        "berry_tree": "BERRY_TREE_ROUTE_29_ORAN",
        "berry_item": "ITEM_ORAN_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_30_1": {
        "berry_tree": "BERRY_TREE_ROUTE_30_PECHA",
        "berry_item": "ITEM_PECHA_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_30_2": {
        "berry_tree": "BERRY_TREE_ROUTE_30_ORAN",
        "berry_item": "ITEM_ORAN_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_31": {
        "berry_tree": "BERRY_TREE_ROUTE_31_PERSIM",
        "berry_item": "ITEM_PERSIM_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_VIOLET_CITY": {
        "berry_tree": "BERRY_TREE_VIOLET_CITY_CHERI",
        "berry_item": "ITEM_CHERI_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_33": {
        "berry_tree": "BERRY_TREE_ROUTE_33_PECHA",
        "berry_item": "ITEM_PECHA_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_AZALEA_TOWN": {
        "berry_tree": "BERRY_TREE_AZALEA_TOWN_LUM",
        "berry_item": "ITEM_LUM_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_35": {
        "berry_tree": "BERRY_TREE_ROUTE_35_LEPPA",
        "berry_item": "ITEM_LEPPA_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_36": {
        "berry_tree": "BERRY_TREE_ROUTE_36_RAWST",
        "berry_item": "ITEM_RAWST_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_37_1": {
        "berry_tree": "BERRY_TREE_ROUTE_37_CHERI",
        "berry_item": "ITEM_CHERI_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_37_2": {
        "berry_tree": "BERRY_TREE_ROUTE_37_ORAN",
        "berry_item": "ITEM_ORAN_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_37_3": {
        "berry_tree": "BERRY_TREE_ROUTE_37_PERSIM",
        "berry_item": "ITEM_PERSIM_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_38": {
        "berry_tree": "BERRY_TREE_ROUTE_38_ORAN",
        "berry_item": "ITEM_ORAN_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_39": {
        "berry_tree": "BERRY_TREE_ROUTE_39_CHESTO",
        "berry_item": "ITEM_CHESTO_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_42_1": {
        "berry_tree": "BERRY_TREE_ROUTE_42_PECHA",
        "berry_item": "ITEM_PECHA_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_42_2": {
        "berry_tree": "BERRY_TREE_ROUTE_42_RAWST",
        "berry_item": "ITEM_RAWST_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_42_3": {
        "berry_tree": "BERRY_TREE_ROUTE_42_SITRUS",
        "berry_item": "ITEM_SITRUS_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_43": {
        "berry_tree": "BERRY_TREE_ROUTE_43_PERSIM",
        "berry_item": "ITEM_PERSIM_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_44": {
        "berry_tree": "BERRY_TREE_ROUTE_44_ASPEAR",
        "berry_item": "ITEM_ASPEAR_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_45": {
        "berry_tree": "BERRY_TREE_ROUTE_45_LEPPA",
        "berry_item": "ITEM_LEPPA_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_26": {
        "berry_tree": "BERRY_TREE_ROUTE_26_RAWST",
        "berry_item": "ITEM_RAWST_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_46_1": {
        "berry_tree": "BERRY_TREE_ROUTE_46_CHERI",
        "berry_item": "ITEM_CHERI_BERRY",
        "needs_soil": True,
    },
    "FRUITTREE_ROUTE_46_2": {
        "berry_tree": "BERRY_TREE_ROUTE_46_ORAN",
        "berry_item": "ITEM_ORAN_BERRY",
        "needs_soil": True,
    },
}
JOHTO_BERRY_TREES_BY_CONSTANT = {info["berry_tree"]: info for info in JOHTO_BERRY_TREES.values()}

CRYSTAL_ITEM_SUBSTITUTIONS = {
    "ITEM_PARLYZ_HEAL": "ITEM_PARALYZE_HEAL",
    "ITEM_ELIXER": "ITEM_ELIXIR",
    "ITEM_MAX_ELIXER": "ITEM_MAX_ELIXIR",
    "ITEM_ENERGYPOWDER": "ITEM_ENERGY_POWDER",
    "ITEM_NEVERMELTICE": "ITEM_NEVER_MELT_ICE",
    "ITEM_FLOWER_MAIL": "ITEM_GLITTER_MAIL",
    "ITEM_SURF_MAIL": "ITEM_WAVE_MAIL",
    "ITEM_RAGECANDYBAR": "ITEM_LAVA_COOKIE",
    "ITEM_S_S_TICKET": "ITEM_SS_TICKET",
    "ITEM_BERRY": "ITEM_ORAN_BERRY",
    "ITEM_GOLD_BERRY": "ITEM_SITRUS_BERRY",
    "ITEM_MYSTERYBERRY": "ITEM_LEPPA_BERRY",
    "ITEM_BITTER_BERRY": "ITEM_PERSIM_BERRY",
    "ITEM_PRZCUREBERRY": "ITEM_CHERI_BERRY",
    "ITEM_PSNCUREBERRY": "ITEM_PECHA_BERRY",
    "ITEM_EON_MAIL": "ITEM_HARBOR_MAIL",
    "ITEM_BLACKBELT_I": "ITEM_BLACK_BELT",
    "ITEM_BLACKGLASSES": "ITEM_BLACK_GLASSES",
    "ITEM_PINK_BOW": "ITEM_SILK_SCARF",
    # Crystal-only TMs fall back to close Emerald-native substitutes for now.
    "ITEM_TM_SWIFT": "ITEM_TM34",
    "ITEM_TM_SLEEP_TALK": "ITEM_TM44",
    "ITEM_TM_SNORE": "ITEM_TM44",
    "ITEM_TM_DETECT": "ITEM_TM17",
    "ITEM_TM_ENDURE": "ITEM_TM17",
    "ITEM_TM_DEFENSE_CURL": "ITEM_TM33",
    "ITEM_TM_ROLLOUT": "ITEM_TM39",
    "ITEM_TM_SWAGGER": "ITEM_TM12",
    "ITEM_TM_DRAGONBREATH": "ITEM_TM02",
    "ITEM_TM_DYNAMICPUNCH": "ITEM_TM01",
    "ITEM_TM_FURY_CUTTER": "ITEM_TM31",
    "ITEM_TM_HEADBUTT": "ITEM_TM08",
    "ITEM_TM_ICY_WIND": "ITEM_TM13",
    "ITEM_TM_MUD_SLAP": "ITEM_TM39",
    "ITEM_TM_ROCK_SMASH": "ITEM_HM06",
    "ITEM_TM_NIGHTMARE": "ITEM_TM41",
    "ITEM_TM_SWEET_SCENT": "ITEM_TM19",
    "ITEM_HM_WHIRLPOOL": "ITEM_HM03",
}

TMHM_LINE_RE = re.compile(r"F\(([A-Z0-9_]+)\)")
MART_CONST_RE = re.compile(r"^\s*const\s+(MART_[A-Z0-9_]+)\s*$")
MART_POINTER_RE = re.compile(r"^\s*dw\s+([A-Za-z0-9_]+)\s*$")
MART_ITEM_RE = re.compile(r"^\s*db\s+(-?[A-Z0-9_]+)")


def load_tmhm_item_maps():
    tm_map = {}
    hm_map = {}
    mode = None
    tm_index = 1
    hm_index = 1
    for raw_line in (ROOT / "include" / "constants" / "tms_hms.h").read_text().splitlines():
        line = raw_line.strip()
        if line.startswith("#define FOREACH_TM("):
            mode = "tm"
            continue
        if line.startswith("#define FOREACH_HM("):
            mode = "hm"
            continue
        if line.startswith("#define FOREACH_TMHM("):
            mode = None
            continue

        match = TMHM_LINE_RE.search(line)
        if match is None or mode is None:
            continue

        move_name = match.group(1)
        if mode == "tm":
            tm_map[move_name] = f"ITEM_TM{tm_index:02d}"
            tm_index += 1
        else:
            hm_map[move_name] = f"ITEM_HM{hm_index:02d}"
            hm_index += 1

    return tm_map, hm_map


TM_ITEM_BY_MOVE, HM_ITEM_BY_MOVE = load_tmhm_item_maps()


def load_crystal_marts():
    mart_constants = []
    for raw_line in CRYSTAL_MART_CONSTANTS_PATH.read_text().splitlines():
        line = raw_line.split(";", 1)[0].strip()
        match = MART_CONST_RE.match(line)
        if match is not None:
            mart_constants.append(match.group(1))

    mart_labels = []
    in_table = False
    for raw_line in CRYSTAL_MARTS_PATH.read_text().splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if line == "Marts:":
            in_table = True
            continue
        if not in_table:
            continue
        if line.startswith("assert_table_length"):
            break
        match = MART_POINTER_RE.match(line)
        if match is not None:
            mart_labels.append(match.group(1))

    if len(mart_constants) != len(mart_labels):
        raise RuntimeError(f"mart constant/table mismatch: {len(mart_constants)} constants vs {len(mart_labels)} labels")

    label_to_items = {}
    current_label = None
    skip_count = False
    for raw_line in CRYSTAL_MARTS_PATH.read_text().splitlines():
        line = raw_line.split(";", 1)[0].strip()
        if not line:
            continue
        if line.endswith(":"):
            current_label = line[:-1]
            if current_label in mart_labels:
                label_to_items[current_label] = []
                skip_count = True
            else:
                current_label = None
            continue
        if current_label is None:
            continue
        match = MART_ITEM_RE.match(line)
        if match is None:
            continue
        token = match.group(1)
        if skip_count:
            skip_count = False
            continue
        if token == "-1":
            current_label = None
            continue
        label_to_items[current_label].append(normalize_item_constant(token))

    marts = {}
    for mart_constant, mart_label in zip(mart_constants, mart_labels):
        marts[mart_constant] = label_to_items.get(mart_label, [])
    return marts


CRYSTAL_MARTS = None


def resolve_target_by_crystal_map(target_map_index, crystal_map: str):
    return target_map_index["by_crystal_map"].get(crystal_map)


def resolve_target_by_crystal_map_id(target_map_index, crystal_map_id: str):
    return target_map_index["by_crystal_map_id"].get(crystal_map_id)


def generated_asset_label(entry, original_label: str) -> str:
    return f"Crystal_{entry['target_name']}_{original_label}"


def generated_script_label(entry, original_label: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", original_label)
    return f"JohtoScript_{entry['target_name']}_{sanitized}"


CRYSTAL_TO_EMERALD_DIR = {
    "UP": "DIR_NORTH",
    "DOWN": "DIR_SOUTH",
    "LEFT": "DIR_WEST",
    "RIGHT": "DIR_EAST",
}

RAW_TRANSLATABLE_COMMANDS = {
    "appear",
    "applymovement",
    "call",
    "checkevent",
    "checkflag",
    "checkitem",
    "clearflag",
    "clearevent",
    "closetext",
    "cry",
    "disappear",
    "end",
    "faceplayer",
    "giveitem",
    "gettrainername",
    "ifequal",
    "iffalse",
    "ifgreater",
    "ifless",
    "ifnotequal",
    "iftrue",
    "jump",
    "jumpstd",
    "moveobject",
    "opentext",
    "pause",
    "playmusic",
    "playsound",
    "promptbutton",
    "readvar",
    "return",
    "scall",
    "setevent",
    "setflag",
    "setval",
    "sjump",
    "special",
    "specialvar",
    "takeitem",
    "turnobject",
    "verbosegiveitem",
    "waitbutton",
    "waitsfx",
    "writetext",
    "yesorno",
}

RAW_BRANCH_COMMANDS = {
    "call",
    "ifequal",
    "iffalse",
    "ifgreater",
    "ifless",
    "ifnotequal",
    "iftrue",
    "jump",
    "scall",
    "sjump",
}

RAW_COMMAND_ALIASES = {
    "jump": "goto",
    "sjump": "goto",
    "scall": "call",
}

RAW_TERMINATING_COMMANDS = {
    "end",
    "jump",
    "jumpstd",
    "return",
    "sjump",
}


def crystal_object_local_id(object_const: str) -> str:
    sanitized = re.sub(r"[^A-Z0-9_]", "_", object_const.upper())
    return f"LOCALID_{sanitized}"


def crystal_object_local_id_map(ir):
    return {
        object_const: crystal_object_local_id(object_const)
        for object_const in ir.get("object_consts", [])
    }


def object_local_ids_for_script(ir, script_label: str):
    local_ids = []
    for event, object_const in zip(ir["events"]["object_events"], ir.get("object_consts", [])):
        if event["script"] == script_label:
            local_ids.append(crystal_object_local_id(object_const))
    return local_ids


def normalize_species_constant(species_name: str) -> str:
    if species_name.startswith("SPECIES_"):
        species_constant = species_name
    else:
        species_constant = f"SPECIES_{species_name}"
    return RAW_SPECIES_ALIASES.get(species_constant, species_constant)


def normalize_item_constant(item_name: str) -> str:
    if item_name.startswith("ITEM_"):
        item_constant = item_name
    else:
        item_constant = f"ITEM_{item_name}"

    item_constant = CRYSTAL_ITEM_SUBSTITUTIONS.get(item_constant, item_constant)

    if item_constant.startswith("ITEM_TM_"):
        move_name = item_constant[len("ITEM_TM_"):]
        return TM_ITEM_BY_MOVE.get(move_name, item_constant)

    if item_constant.startswith("ITEM_HM_"):
        move_name = item_constant[len("ITEM_HM_"):]
        return HM_ITEM_BY_MOVE.get(move_name, item_constant)

    return item_constant


def get_crystal_marts():
    global CRYSTAL_MARTS
    if CRYSTAL_MARTS is None:
        CRYSTAL_MARTS = load_crystal_marts()
    return CRYSTAL_MARTS


def normalize_music_constant(song_name: str) -> str:
    return RAW_MUSIC_ALIASES.get(song_name, song_name)


def normalize_sound_constant(sound_name: str) -> str:
    return RAW_SOUND_ALIASES.get(sound_name, sound_name)


def berry_tree_info_from_fruittree(fruittree_name: str):
    info = JOHTO_BERRY_TREES.get(fruittree_name)
    if info is None:
        return None

    berry_tree = info["berry_tree"]
    if berry_tree not in BERRY_TREE_CONSTANTS:
        raise ValueError(f"missing berry tree constant '{berry_tree}' for {fruittree_name}")
    return info


def berry_tree_constant_from_fruittree(fruittree_name: str):
    info = berry_tree_info_from_fruittree(fruittree_name)
    if info is None:
        return None
    return info["berry_tree"]


def berry_soil_mapgrid_entry(elevation: int) -> int:
    return EMERALD_BERRY_SOIL_METATILE_ID | MAPGRID_IMPASSABLE | (elevation << 12)


def stamp_johto_berry_soil(metatile_rows, map_data):
    height = len(metatile_rows)
    width = len(metatile_rows[0]) if height else 0

    for event in map_data.get("object_events", []):
        berry_tree = event.get("trainer_sight_or_berry_tree_id")
        if event.get("movement_type") != "MOVEMENT_TYPE_BERRY_TREE_GROWTH":
            continue
        if berry_tree not in JOHTO_BERRY_TREES_BY_CONSTANT:
            continue
        if not JOHTO_BERRY_TREES_BY_CONSTANT[berry_tree]["needs_soil"]:
            continue

        x = int(event["x"])
        y = int(event["y"])
        if not (0 <= x < width and 0 <= y < height):
            raise ValueError(f"{map_data['name']}: berry soil position {(x, y)} is out of bounds")

        metatile_rows[y][x] = berry_soil_mapgrid_entry(int(event.get("elevation", 3)))


def apply_text_substitutions(value: str) -> str:
    for source, target in TEXT_SUBSTITUTIONS:
        value = value.replace(source, target)
    # Crystal uses "#" as a POKe prefix marker in many compounds
    # (for example "# BALL", "#MANIAC", "# SEER"), and "@" as an
    # inline join marker around text_ram/text_start boundaries.
    value = value.replace("#", "POKé")
    value = value.replace("@", "")
    return value


def escape_emerald_string(value: str) -> str:
    return value.replace('"', '\\"')


def load_text_numeric_constants(ir):
    source_asm = ir.get("source_asm")
    cached = TEXT_NUMERIC_CONSTANTS_CACHE.get(source_asm)
    if cached is not None:
        return cached

    constants = dict(GLOBAL_TEXT_NUMERIC_CONSTANTS)
    if source_asm:
        source_path = CRYSTAL_ROOT / source_asm
        if source_path.exists():
            for raw_line in source_path.read_text().splitlines():
                line = raw_line.split(";", 1)[0].strip()
                match = LOCAL_TEXT_CONSTANT_RE.match(line)
                if match is None:
                    continue
                constants.setdefault(match.group(1), match.group(2))

    TEXT_NUMERIC_CONSTANTS_CACHE[source_asm] = constants
    return constants


def resolve_decimal_text_placeholders(value: str, numeric_constants):
    unresolved = []

    def replacer(match):
        constant_name = match.group(1)
        replacement = numeric_constants.get(constant_name)
        if replacement is None:
            unresolved.append(f"decimal {constant_name}")
            return match.group(0)
        return replacement

    return DECIMAL_TEXT_PLACEHOLDER_RE.sub(replacer, value), unresolved


TEXT_COMMAND_NAMES = {
    "if",
    "else",
    "endc",
    "text",
    "line",
    "cont",
    "para",
    "page",
    "text_ram",
    "text_start",
    "done",
    "prompt",
}

TEXT_LITERAL_RE = re.compile(r'^[a-z_]+\s+"(.*)"$')


def text_block_like(block):
    commands = block.get("commands", [])
    return bool(commands) and all(command.get("command") in TEXT_COMMAND_NAMES for command in commands)


def get_text_block(ir, text_label: str):
    text_block = ir["texts"].get(text_label)
    if text_block is not None:
        return text_block

    script_block = ir["scripts"].get(text_label)
    if script_block is not None and text_block_like(script_block):
        return script_block

    return None


def extract_text_command_value(command):
    if "value" in command:
        return command["value"]

    raw = command.get("raw", "")
    literal_match = TEXT_LITERAL_RE.match(raw)
    if literal_match is not None:
        return literal_match.group(1)

    args = command.get("args", [])
    if args:
        return args[0].strip('"')

    return ""


def normalize_text_commands(text_block):
    commands = [
        {
            "command": command["command"],
            "value": extract_text_command_value(command),
            "raw": command.get("raw", ""),
        }
        for command in text_block["commands"]
    ]

    if commands and commands[0]["command"] == "if":
        else_index = next((i for i, command in enumerate(commands) if command["command"] == "else"), None)
        endc_index = next((i for i, command in enumerate(commands) if command["command"] == "endc"), None)
        if else_index is not None and endc_index is not None and else_index < endc_index:
            condition = commands[0]["raw"]
            if "_CRYSTAL_AU" in condition:
                commands = commands[else_index + 1:endc_index]
            else:
                commands = commands[1:else_index]

    return commands


def convert_text_block(text_block, numeric_constants=None):
    composed = ""
    unsupported = []
    prefix_map = {
        "text": "",
        "line": "\\n",
        "cont": "\\n",
        "para": "\\p",
        "page": "\\p",
    }

    for command in normalize_text_commands(text_block):
        name = command["command"]
        value = command["value"]

        if name in prefix_map:
            if value == "@":
                value = ""
            composed += prefix_map[name] + value
        elif name == "text_ram":
            placeholder = TEXT_RAM_PLACEHOLDERS.get(value)
            if placeholder is None:
                unsupported.append(f"{name} {value}")
            else:
                composed += placeholder
        elif name in {"done", "prompt", "text_start"}:
            continue
        else:
            unsupported.append(name if not value else f"{name} {value}")

    if unsupported or not composed:
        return None, unsupported

    rendered = apply_text_substitutions(composed)
    rendered, unresolved_decimal = resolve_decimal_text_placeholders(rendered, numeric_constants or {})
    if unresolved_decimal:
        return None, unresolved_decimal
    if "#" in rendered or "@" in rendered:
        unresolved = []
        if "#" in rendered:
            unresolved.append("untranslated # token")
        if "@" in rendered:
            unresolved.append("untranslated @ token")
        return None, unresolved
    unresolved_placeholders = DECIMAL_TEXT_PLACEHOLDER_RE.findall(rendered)
    if unresolved_placeholders:
        return None, [f"decimal {placeholder}" for placeholder in unresolved_placeholders]

    return [rendered + "$"], []


def convert_movement_block(movement_block):
    lines = []
    unsupported = []

    for step in movement_block["steps"]:
        name = step["command"]
        args = step["args"]

        if name == "step_end":
            lines.append("step_end")
            continue

        if name in {"step", "slow_step", "big_step", "turn_head", "jump_step"}:
            if len(args) != 1 or args[0] not in DIRECTION_SUFFIX:
                unsupported.append(f"{name} {' '.join(args)}".strip())
                continue

            direction = DIRECTION_SUFFIX[args[0]]
            mapping = {
                "step": f"walk_{direction}",
                "slow_step": f"walk_slow_{direction}",
                "big_step": f"walk_fast_{direction}",
                "turn_head": f"face_{direction}",
                "jump_step": f"jump_2_{direction}",
            }
            lines.append(mapping[name])
            continue

        if name == "fix_facing":
            lines.append("lock_facing_direction")
            continue

        if name == "remove_fixed_facing":
            lines.append("unlock_facing_direction")
            continue

        unsupported.append(name if not args else f"{name} {' '.join(args)}")

    if unsupported or not lines:
        return None, unsupported

    return lines, []


def crystal_sprite_to_graphics_id(sprite: str, object_type: str) -> str:
    if object_type == "OBJECTTYPE_ITEMBALL":
        return "OBJ_EVENT_GFX_ITEM_BALL"
    return CRYSTAL_SPRITE_GFX.get(sprite, "OBJ_EVENT_GFX_MAN_1")


def crystal_movement_to_type(movement: str, sprite: str) -> str:
    if sprite == "SPRITE_FRUIT_TREE":
        return "MOVEMENT_TYPE_BERRY_TREE_GROWTH"
    return CRYSTAL_MOVEMENT_TYPES.get(movement, "MOVEMENT_TYPE_LOOK_AROUND")


def event_placeholder_text_label(entry) -> str:
    return f"{entry['target_name']}_Text_AutoPlaceholder"


def placeholder_bg_events(entry, ir):
    events = []
    for event in ir["events"]["bg_events"]:
        script = ir["scripts"].get(event["script"])
        if (
            event["kind"] == "BGEVENT_ITEM"
            and script is not None
            and script["first_command"] == "hiddenitem"
            and len(script["commands"][0]["args"]) >= 2
        ):
            item_name, flag_name = script["commands"][0]["args"][:2]
            if flag_name in CONSTANT_NAMES:
                events.append(
                    {
                        "type": "hidden_item",
                        "x": event["x"],
                        "y": event["y"],
                        "elevation": 0,
                        "item": normalize_item_constant(item_name),
                        "flag": flag_name,
                    }
                )
                continue

        events.append(
            {
                "type": "sign",
                "x": event["x"],
                "y": event["y"],
                "elevation": 0,
                "player_facing_dir": CRYSTAL_BG_KIND_TO_FACING.get(event["kind"], "BG_EVENT_PLAYER_FACING_ANY"),
                "script": generated_script_label(entry, event["script"]),
            }
        )
    return events


def placeholder_object_events(entry, ir, count=None, indices=None):
    expected = ir["events"]["object_events"]
    object_consts = ir.get("object_consts", [])
    if indices is not None:
        expected = [expected[index] for index in indices]
        object_consts = [object_consts[index] for index in indices]
    elif count is not None:
        expected = expected[:count]
        object_consts = object_consts[:count]

    events = []
    for crystal, object_const in zip(expected, object_consts):
        trainer_type = "TRAINER_TYPE_NORMAL" if crystal["object_type"] == "OBJECTTYPE_TRAINER" else "TRAINER_TYPE_NONE"
        trainer_value = str(crystal["trainer_sight_range"]) if trainer_type == "TRAINER_TYPE_NORMAL" else "0"
        script_name = generated_script_label(entry, crystal["script"])
        script = ir["scripts"].get(crystal["script"])
        if script is not None and script["first_command"] == "fruittree" and script["commands"][0]["args"]:
            berry_tree_id = berry_tree_constant_from_fruittree(script["commands"][0]["args"][0])
            if berry_tree_id is not None:
                trainer_value = berry_tree_id
                script_name = "BerryTreeScript"
        events.append(
            {
                "local_id": crystal_object_local_id(object_const),
                "graphics_id": crystal_sprite_to_graphics_id(crystal["sprite"], crystal["object_type"]),
                "x": crystal["x"],
                "y": crystal["y"],
                "elevation": 3,
                "movement_type": crystal_movement_to_type(crystal["movement"], crystal["sprite"]),
                "movement_range_x": crystal["movement_range_x"],
                "movement_range_y": crystal["movement_range_y"],
                "trainer_type": trainer_type,
                "trainer_sight_or_berry_tree_id": trainer_value,
                "script": script_name,
                "flag": "0",
            }
        )
    return events


def placeholder_coord_events(entry, ir):
    coord_mode = entry.get("coord_mode")
    if coord_mode == "repeat_values":
        events = []
        for crystal in ir["events"]["coord_events"]:
            for value in entry["coord_repeat_values"]:
                events.append(
                    {
                        "type": "trigger",
                        "x": crystal["x"],
                        "y": crystal["y"],
                        "elevation": 3,
                        "var": entry["coord_repeat_var"],
                        "var_value": value,
                        "script": generated_script_label(entry, crystal["script"]),
                    }
                )
        return events

    return [
        {
            "type": "trigger",
            "x": event["x"],
            "y": event["y"],
            "elevation": 3,
            "var": "VAR_TEMP_0",
            "var_value": "255",
            "script": generated_script_label(entry, event["script"]),
        }
        for event in ir["events"]["coord_events"]
    ]


def placeholder_object_event_count(entry, ir):
    object_mode = entry.get("object_mode")
    if object_mode == "subset" or object_mode == "remap":
        return len(entry["object_indices"])
    return len(ir["events"]["object_events"])


def simple_text_body(script):
    if script is None:
        return None

    commands = script["commands"]
    index = 0

    if index < len(commands) and commands[index]["command"] == "endifjustbattled":
        index += 1
    if index < len(commands) and commands[index]["command"] == "opentext":
        index += 1
    if index >= len(commands) or commands[index]["command"] != "writetext" or not commands[index]["args"]:
        return None

    text_label = commands[index]["args"][0]
    index += 1
    while index < len(commands) and commands[index]["command"] in {"waitbutton", "promptbutton"}:
        index += 1
    if index >= len(commands) or commands[index]["command"] != "closetext":
        return None
    index += 1
    if index >= len(commands) or commands[index]["command"] != "end":
        return None
    index += 1
    if index != len(commands):
        return None

    return text_label


def render_simple_msgbox_script(entry, script_label: str, text_label: str, category: str, faceplayer=False):
    msgbox_kind = "MSGBOX_SIGN" if category == "bg" else "MSGBOX_DEFAULT"
    lines = [f"{generated_script_label(entry, script_label)}::"]
    if category == "object":
        lines.append("\tlock")
        if faceplayer:
            lines.append("\tfaceplayer")
    lines.append(f"\tmsgbox {generated_asset_label(entry, text_label)}, {msgbox_kind}")
    if category == "object":
        lines.append("\trelease")
    lines.append("\tend")
    lines.append("")
    return lines


def simple_text_script_plan(entry, ir, script_label: str):
    script = ir["scripts"].get(script_label)
    if script is None:
        return None
    commands = script["commands"]
    command_names = [command["command"] for command in commands]

    if command_names == ["jumptext"] and commands[0]["args"]:
        return {
            "type": "simple_text",
            "text_label": commands[0]["args"][0],
            "needs_faceplayer": False,
        }

    if command_names == ["jumptextfaceplayer"] and commands[0]["args"]:
        return {
            "type": "simple_text",
            "text_label": commands[0]["args"][0],
            "needs_faceplayer": True,
        }

    needs_faceplayer = False
    if commands and commands[0]["command"] == "faceplayer":
        needs_faceplayer = True
        commands = commands[1:]

    text_label = simple_text_body({"commands": commands})
    if text_label is None:
        return None

    text_block = get_text_block(ir, text_label)
    if text_block is None:
        return None

    fragments, unsupported = convert_text_block(text_block, load_text_numeric_constants(ir))
    if unsupported:
        return None

    return {
        "type": "simple_text",
        "text_label": text_label,
        "needs_faceplayer": needs_faceplayer,
    }


def conditional_text_script_plan(entry, ir, script_label: str):
    script = ir["scripts"].get(script_label)
    if script is None:
        return None

    commands = script["commands"]
    index = 0
    needs_faceplayer = False
    if index < len(commands) and commands[index]["command"] == "faceplayer":
        needs_faceplayer = True
        index += 1
    if index >= len(commands) or commands[index]["command"] != "opentext":
        return None
    index += 1
    if index + 5 >= len(commands):
        return None

    check_command = commands[index]
    branch_command = commands[index + 1]
    text_command = commands[index + 2]
    if check_command["command"] not in {"checkevent", "checkflag"} or not check_command["args"]:
        return None
    if check_command["args"][0] not in CONSTANT_NAMES:
        return None
    if branch_command["command"] not in {"iftrue", "iffalse"} or not branch_command["args"]:
        return None
    if text_command["command"] != "writetext" or not text_command["args"]:
        return None
    if commands[index + 3]["command"] not in {"waitbutton", "promptbutton"}:
        return None
    if commands[index + 4]["command"] != "closetext" or commands[index + 5]["command"] != "end":
        return None
    if index + 6 != len(commands):
        return None

    branch_label = branch_command["args"][0]
    branch_text_label = simple_text_body(ir["scripts"].get(branch_label))
    if branch_text_label is None:
        return None

    main_text_block = get_text_block(ir, text_command["args"][0])
    branch_text_block = get_text_block(ir, branch_text_label)
    if main_text_block is None or branch_text_block is None:
        return None

    main_fragments, main_unsupported = convert_text_block(main_text_block, load_text_numeric_constants(ir))
    branch_fragments, branch_unsupported = convert_text_block(branch_text_block, load_text_numeric_constants(ir))
    if main_unsupported or branch_unsupported:
        return None

    return {
        "type": "conditional_text",
        "check_kind": check_command["command"],
        "check_target": check_command["args"][0],
        "branch_on_true": branch_command["command"] == "iftrue",
        "main_text_label": text_command["args"][0],
        "branch_text_label": branch_text_label,
        "needs_faceplayer": needs_faceplayer,
    }


def text_label_is_supported(ir, text_label: str) -> bool:
    text_block = get_text_block(ir, text_label)
    if text_block is None:
        return False
    _, unsupported = convert_text_block(text_block, load_text_numeric_constants(ir))
    return not unsupported


def trainer_followup_text_label(commands):
    for command in commands:
        if command["command"] in {"trainer", ".Script", "loadvar", "endifjustbattled", "opentext", "faceplayer"}:
            continue
        if command["command"] in {"writetext", "jumptext", "jumptextfaceplayer"} and command["args"]:
            return command["args"][0]
    return None


def trainer_script_plan(entry, ir, script_label: str):
    script = ir["scripts"].get(script_label)
    if script is None or not script["commands"] or script["commands"][0]["command"] != "trainer":
        return None

    args = script["commands"][0]["args"]
    if len(args) < 5:
        return None

    trainer_class, trainer_name = args[0], args[1]
    seen_text_label, beaten_text_label = args[3], args[4]
    if not text_label_is_supported(ir, seen_text_label) or not text_label_is_supported(ir, beaten_text_label):
        return None

    followup_text_label = trainer_followup_text_label(script["commands"][1:])
    if followup_text_label is None and len(args) >= 7 and args[6] != "0":
        followup_script = ir["scripts"].get(args[6])
        if followup_script is not None:
            followup_text_label = trainer_followup_text_label(followup_script["commands"])
    if followup_text_label is not None and not text_label_is_supported(ir, followup_text_label):
        followup_text_label = None

    trainer_constant = trainer_constant_name(trainer_class, trainer_name)
    lines = [f"{generated_script_label(entry, script_label)}::"]

    if followup_text_label is None:
        lines.append(
            f"\ttrainerbattle_single {trainer_constant}, "
            f"{generated_asset_label(entry, seen_text_label)}, "
            f"{generated_asset_label(entry, beaten_text_label)}"
        )
        lines.append("")
        return lines

    callback_label = f"{generated_script_label(entry, script_label)}_AfterBattle"
    lines.append(
        f"\ttrainerbattle_single {trainer_constant}, "
        f"{generated_asset_label(entry, seen_text_label)}, "
        f"{generated_asset_label(entry, beaten_text_label)}, "
        f"{callback_label}"
    )
    lines.extend(
        [
            "",
            f"{callback_label}::",
            f"\tmsgbox {generated_asset_label(entry, followup_text_label)}, MSGBOX_DEFAULT",
            "\tend",
            "",
        ]
    )
    return lines


def mart_label_name(entry, script_label: str) -> str:
    return f"{generated_script_label(entry, script_label)}_Pokemart"


def pokemart_script_plan(entry, ir, script_label: str):
    script = ir["scripts"].get(script_label)
    if script is None:
        return None

    commands = script["commands"]
    index = 0
    needs_faceplayer = False
    if index < len(commands) and commands[index]["command"] == "faceplayer":
        needs_faceplayer = True
        index += 1
    if index + 4 != len(commands):
        return None
    if commands[index]["command"] != "opentext":
        return None
    mart_command = commands[index + 1]
    if mart_command["command"] != "pokemart" or len(mart_command["args"]) < 2:
        return None
    if commands[index + 2]["command"] != "closetext" or commands[index + 3]["command"] != "end":
        return None

    mart_id = mart_command["args"][1]
    mart_items = get_crystal_marts().get(mart_id)
    if not mart_items:
        return None

    return {
        "type": "pokemart",
        "needs_faceplayer": needs_faceplayer,
        "mart_id": mart_id,
        "items": mart_items,
    }


def special_script_plan(entry, ir, script_label: str):
    script = ir["scripts"].get(script_label)
    if script is None or not script["commands"]:
        return None

    command_names = [command["command"] for command in script["commands"]]
    if command_names == ["faceplayer", "opentext", "special", "waitbutton", "closetext", "end"]:
        special_name = script["commands"][2]["args"][0] if script["commands"][2]["args"] else None
        if special_name == "NameRater":
            return {
                "type": "goto",
                "target": "SlateportCity_NameRatersHouse_EventScript_NameRater",
            }

    pokemart_plan = pokemart_script_plan(entry, ir, script_label)
    if pokemart_plan is not None:
        return pokemart_plan

    first_command = script["commands"][0]
    command_name = first_command["command"]

    if command_name == "itemball" and first_command["args"]:
        return {
            "type": "itemball",
            "item": normalize_item_constant(first_command["args"][0]),
        }

    if command_name == "hiddenitem" and len(first_command["args"]) >= 2:
        return {
            "type": "hiddenitem",
            "item": normalize_item_constant(first_command["args"][0]),
            "flag": first_command["args"][1],
        }

    if command_name == "fruittree":
        return {
            "type": "goto",
            "target": "BerryTreeScript",
        }

    if command_name == "jumpstd" and first_command["args"]:
        if first_command["args"][0] == "PokecenterNurseScript":
            local_ids = object_local_ids_for_script(ir, script_label)
            if len(local_ids) == 1:
                return {
                    "type": "pokecenter_nurse",
                    "local_id": local_ids[0],
                }
        target = STANDARD_GOTO_SCRIPTS.get(first_command["args"][0])
        if target is not None and len(script["commands"]) in {1, 2}:
            trailing = [command["command"] for command in script["commands"][1:]]
            if not trailing or trailing == ["end"]:
                return {
                    "type": "goto",
                    "target": target,
                }

    return None


def can_render_generated_text(ir, text_label: str) -> bool:
    text_block = get_text_block(ir, text_label)
    if text_block is None:
        return False
    fragments, unsupported = convert_text_block(text_block, load_text_numeric_constants(ir))
    return fragments is not None and not unsupported


def can_render_generated_movement(ir, movement_label: str) -> bool:
    movement_block = ir["movements"].get(movement_label)
    if movement_block is None:
        return False
    movement_lines, unsupported = convert_movement_block(movement_block)
    return movement_lines is not None and not unsupported


def script_text_command_refs(script):
    refs = []
    for command in script.get("commands", []):
        if command["command"] in {"writetext", "jumptext", "jumptextfaceplayer"} and command.get("args"):
            refs.append(command["args"][0])
    return refs


def script_movement_command_refs(script):
    refs = []
    for command in script.get("commands", []):
        if command["command"] == "applymovement" and len(command.get("args", [])) >= 2:
            refs.append(command["args"][1])
    return refs


def normalize_raw_object_arg(ir, arg: str) -> str:
    if arg == "PLAYER":
        return "LOCALID_PLAYER"
    if arg == "LAST_TALKED":
        return "VAR_LAST_TALKED"
    return crystal_object_local_id_map(ir).get(arg, arg)


def normalize_raw_value_arg(arg: str) -> str:
    return RAW_VALUE_ALIASES.get(arg, arg)


def normalize_string_buffer_arg(arg: str) -> Optional[str]:
    return CRYSTAL_STRING_BUFFER_ALIASES.get(arg)


def can_render_raw_command(command) -> bool:
    name = command["command"]
    args = list(command["args"])
    if name not in RAW_TRANSLATABLE_COMMANDS:
        return False
    if name == "gettrainername":
        return (
            len(args) >= 3
            and normalize_string_buffer_arg(args[0]) is not None
            and trainer_constant_name(args[1], args[2]) in CONSTANT_NAMES
        )
    if name == "jumpstd":
        return bool(args) and args[0] in STANDARD_GOTO_SCRIPTS
    if name == "special":
        return bool(args) and (args[0] in AVAILABLE_SPECIALS or args[0] in RAW_SPECIAL_TRANSLATIONS)
    return True


def render_raw_script_command(entry, ir, script_categories, command):
    name = command["command"]
    args = list(command["args"])
    rendered_name = RAW_COMMAND_ALIASES.get(name, name)

    if name == "readvar":
        translated_lines = RAW_READVAR_TRANSLATIONS.get(args[0]) if args else None
        if translated_lines is not None:
            return [f"\t{line}" for line in translated_lines]
    if name == "special":
        translated_lines = RAW_SPECIAL_TRANSLATIONS.get(args[0])
        if translated_lines is not None:
            return [f"\t{line}" for line in translated_lines]

    if name == "writetext":
        args = [generated_asset_label(entry, args[0])]
    elif name == "applymovement":
        args = [normalize_raw_object_arg(ir, args[0]), generated_asset_label(entry, args[1])]
    elif name == "turnobject":
        args = [normalize_raw_object_arg(ir, args[0]), CRYSTAL_TO_EMERALD_DIR.get(args[1], args[1])]
    elif name == "moveobject":
        args = [normalize_raw_object_arg(ir, args[0]), args[1], args[2]]
    elif name in {"appear", "disappear"}:
        args = [normalize_raw_object_arg(ir, args[0])]
    elif name in {"jump", "sjump", "call", "scall", "iftrue", "iffalse"}:
        args = [generated_script_label(entry, args[0])]
    elif name in {"ifequal", "ifnotequal", "ifgreater", "ifless"}:
        args = [normalize_raw_value_arg(args[0]), generated_script_label(entry, args[1])]
    elif name in {"giveitem", "verbosegiveitem", "checkitem", "takeitem"}:
        args = [normalize_item_constant(args[0]), *args[1:]]
    elif name == "cry":
        args = [normalize_species_constant(args[0])]
    elif name == "playmusic":
        args = [normalize_music_constant(args[0])]
    elif name == "playsound":
        args = [normalize_sound_constant(args[0])]
    elif name == "setval":
        args = [normalize_raw_value_arg(args[0])]
    elif name == "gettrainername":
        rendered_name = "buffertrainername"
        args = [normalize_string_buffer_arg(args[0]), trainer_constant_name(args[1], args[2])]
    elif name == "jumpstd":
        rendered_name = "goto"
        args = [STANDARD_GOTO_SCRIPTS[args[0]]]

    return f"\t{rendered_name}" if not args else f"\t{rendered_name} {', '.join(args)}"


def raw_script_plan(entry, ir, script_label: str, script_categories):
    reachable_labels = []
    reachable_set = set()
    stack = [script_label]

    while stack:
        current = stack.pop()
        if current in reachable_set:
            continue

        script = ir["scripts"].get(current)
        if script is None:
            return None
        if any(not can_render_raw_command(command) for command in script["commands"]):
            return None
        if not script["commands"]:
            return None
        if script["commands"][-1]["command"] not in RAW_TERMINATING_COMMANDS and script.get("fallthrough_label") is None:
            return None
        if any(not can_render_generated_text(ir, text_label) for text_label in script.get("text_refs", [])):
            return None
        if any(not can_render_generated_movement(ir, movement_label) for movement_label in script.get("movement_refs", [])):
            return None

        reachable_set.add(current)
        reachable_labels.append(current)
        for label_ref in script.get("label_refs", []):
            if label_ref in script_categories and label_ref != script_label:
                continue
            stack.append(label_ref)

    ordered_labels = []
    emitted = set()

    def emit_order(current):
        if current in emitted:
            return
        emitted.add(current)
        ordered_labels.append(current)
        for label_ref in ir["scripts"][current].get("label_refs", []):
            if label_ref in reachable_set:
                emit_order(label_ref)

    emit_order(script_label)

    lines = []
    for current in ordered_labels:
        lines.append(f"{generated_script_label(entry, current)}::")
        for command in ir["scripts"][current]["commands"]:
            rendered = render_raw_script_command(entry, ir, script_categories, command)
            if isinstance(rendered, list):
                lines.extend(rendered)
            else:
                lines.append(rendered)
        lines.append("")

    return lines


def compile_script_plan(entry, ir, script_label: str, category: str, script_categories):
    trainer_plan = trainer_script_plan(entry, ir, script_label)
    if trainer_plan is not None:
        return trainer_plan

    special_plan = special_script_plan(entry, ir, script_label)
    if special_plan is not None:
        if special_plan["type"] == "itemball":
            return [
                f"{generated_script_label(entry, script_label)}::",
                f"\tfinditem {special_plan['item']}",
                "\tend",
                "",
            ]
        if special_plan["type"] == "hiddenitem":
            return [
                f"{generated_script_label(entry, script_label)}::",
                f"\tsetorcopyvar VAR_0x8004, {special_plan['flag']}",
                f"\tsetorcopyvar VAR_0x8005, {special_plan['item']}",
                "\tgoto EventScript_HiddenItemScript",
                "",
            ]
        if special_plan["type"] == "pokecenter_nurse":
            return [
                f"{generated_script_label(entry, script_label)}::",
                f"\tsetorcopyvar VAR_0x800B, {special_plan['local_id']}",
                "\tcall Common_EventScript_PkmnCenterNurse",
                "\twaitmessage",
                "\twaitbuttonpress",
                "\trelease",
                "\tend",
                "",
            ]
        if special_plan["type"] == "pokemart":
            mart_label = mart_label_name(entry, script_label)
            lines = [
                f"{generated_script_label(entry, script_label)}::",
                "\tlock",
            ]
            if special_plan["needs_faceplayer"]:
                lines.append("\tfaceplayer")
            else:
                lines.append("\tfaceplayer")
            lines.extend(
                [
                    "\tmessage gText_HowMayIServeYou",
                    "\twaitmessage",
                    f"\tpokemart {mart_label}",
                    "\tmsgbox gText_PleaseComeAgain, MSGBOX_DEFAULT",
                    "\trelease",
                    "\tend",
                    "",
                    "\t.align 2",
                    f"{mart_label}:",
                ]
            )
            for item in special_plan["items"]:
                lines.append(f"\t.2byte {item}")
            lines.extend(
                [
                    "\tpokemartlistend",
                    "",
                ]
            )
            return lines
        if special_plan["type"] == "goto":
            return [
                f"{generated_script_label(entry, script_label)}::",
                f"\tgoto {special_plan['target']}",
                "",
            ]

    plan = simple_text_script_plan(entry, ir, script_label)
    if plan is not None:
        return render_simple_msgbox_script(
            entry,
            script_label,
            plan["text_label"],
            category,
            faceplayer=plan["needs_faceplayer"],
        )

    conditional_plan = conditional_text_script_plan(entry, ir, script_label)
    if conditional_plan is not None:
        branch_label = f"{generated_script_label(entry, script_label)}_Branch"
        msgbox_kind = "MSGBOX_SIGN" if category == "bg" else "MSGBOX_DEFAULT"
        goto_opcode = "goto_if_set" if conditional_plan["branch_on_true"] else "goto_if_unset"
        lines = [f"{generated_script_label(entry, script_label)}::"]
        if category == "object":
            lines.append("\tlock")
            if conditional_plan["needs_faceplayer"]:
                lines.append("\tfaceplayer")
        lines.append(f"\t{goto_opcode} {conditional_plan['check_target']}, {branch_label}")
        lines.append(f"\tmsgbox {generated_asset_label(entry, conditional_plan['main_text_label'])}, {msgbox_kind}")
        if category == "object":
            lines.append("\trelease")
        lines.append("\tend")
        lines.append("")
        lines.append(f"{branch_label}:")
        lines.append(f"\tmsgbox {generated_asset_label(entry, conditional_plan['branch_text_label'])}, {msgbox_kind}")
        if category == "object":
            lines.append("\trelease")
        lines.append("\tend")
        lines.append("")
        return lines

    raw_plan = raw_script_plan(entry, ir, script_label, script_categories)
    if raw_plan is not None:
        return raw_plan

    return None


def collect_event_script_categories(ir):
    categories = {}

    def register(script_label: str, category: str):
        if SCRIPT_CATEGORY_PRIORITY.get(category, 0) > SCRIPT_CATEGORY_PRIORITY.get(categories.get(script_label, ""), 0):
            categories[script_label] = category

    for event in ir["events"]["object_events"]:
        register(event["script"], "object")
    for event in ir["events"]["coord_events"]:
        register(event["script"], "coord")
    for event in ir["events"]["bg_events"]:
        register(event["script"], "bg")
    return categories


def append_unique_script_blocks(lines, compiled_lines, emitted_labels):
    block_lines = []
    block_label = None

    def flush():
        nonlocal block_lines, block_label
        if not block_lines:
            return
        if block_label is None or block_label not in emitted_labels:
            if block_label is not None:
                emitted_labels.add(block_label)
            lines.extend(block_lines)
        block_lines = []
        block_label = None

    for line in compiled_lines:
        stripped = line.strip()
        if stripped.endswith("::"):
            flush()
            block_label = stripped[:-2]
            block_lines = [line]
            continue
        if stripped.endswith(":") and stripped[:-1]:
            flush()
            block_label = stripped[:-1]
            block_lines = [line]
            continue
        block_lines.append(line)

    flush()


def build_generated_scripts(entry, ir) -> str:
    placeholder_text = event_placeholder_text_label(entry)
    script_categories = collect_event_script_categories(ir)
    emitted_labels = set()
    lines = [
        AUTO_SCRIPT_HEADER,
        "",
        f"{entry['target_name']}_MapScripts::",
        "\t.byte 0",
        "",
        f"{placeholder_text}:",
        '\t.string "This part of Johto is still being restored.$"',
        "",
    ]

    for script_label in sorted(script_categories):
        category = script_categories[script_label]
        compiled_lines = compile_script_plan(entry, ir, script_label, category, script_categories)
        if compiled_lines is not None:
            append_unique_script_blocks(lines, compiled_lines, emitted_labels)
            continue

        lines.append(f"{generated_script_label(entry, script_label)}::")
        if category == "object":
            lines.append("\tlock")
            lines.append("\tfaceplayer")
            lines.append(f"\tmsgbox {placeholder_text}, MSGBOX_DEFAULT")
            lines.append("\trelease")
        else:
            msgbox_kind = "MSGBOX_SIGN" if category == "bg" else "MSGBOX_DEFAULT"
            lines.append(f"\tmsgbox {placeholder_text}, {msgbox_kind}")
        lines.append("\tend")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_generated_script_assets(manifest, ir_index):
    global_text_assets = {}
    global_movement_assets = {}
    for entry in manifest:
        ir = ir_index[entry["crystal_map"]]
        for label, text_block in ir["texts"].items():
            global_text_assets.setdefault(label, text_block)
        for label, script_block in ir["scripts"].items():
            if label not in global_text_assets and text_block_like(script_block):
                global_text_assets[label] = script_block
        for label, movement_block in ir["movements"].items():
            global_movement_assets.setdefault(label, movement_block)

    lines = [
        "@ Generated by scripts/import_johto_maps.py. Do not edit manually.",
        "@ Crystal-authored text and movement assets for imported Johto maps.",
        "",
    ]

    for entry in manifest:
        ir = ir_index[entry["crystal_map"]]
        if not ir["texts"] and not ir["movements"]:
            continue

        lines.append(f"@ {entry['target_name']} <= {entry['crystal_map']}")
        numeric_constants = load_text_numeric_constants(ir)

        text_assets = dict(ir["texts"])
        for label, script_block in ir["scripts"].items():
            if label not in text_assets and text_block_like(script_block):
                text_assets[label] = script_block
        for script_block in ir["scripts"].values():
            text_labels = set(script_block.get("text_refs", []))
            text_labels.update(script_text_command_refs(script_block))
            for text_label in text_labels:
                if text_label not in text_assets and text_label in global_text_assets:
                    text_assets[text_label] = global_text_assets[text_label]

        for label, text_block in text_assets.items():
            fragments, unsupported = convert_text_block(text_block, numeric_constants)
            if unsupported or fragments is None:
                detail = ", ".join(unsupported)
                if not detail:
                    detail = "empty rendered text"
                lines.append(f"@ skipped text asset {label}: unsupported commands {detail}")
                continue

            lines.append(f"{generated_asset_label(entry, label)}:")
            for fragment in fragments:
                lines.append(f'\t.string "{escape_emerald_string(fragment)}"')
            lines.append("")

        movement_assets = dict(ir["movements"])
        for script_block in ir["scripts"].values():
            movement_labels = set(script_block.get("movement_refs", []))
            movement_labels.update(script_movement_command_refs(script_block))
            for movement_label in movement_labels:
                if movement_label not in movement_assets and movement_label in global_movement_assets:
                    movement_assets[movement_label] = global_movement_assets[movement_label]

        for label, movement_block in movement_assets.items():
            movement_lines, unsupported = convert_movement_block(movement_block)
            if unsupported:
                detail = ", ".join(unsupported)
                lines.append(f"@ skipped movement asset {label}: unsupported commands {detail}")
                continue

            lines.append(f"{generated_asset_label(entry, label)}:")
            for movement_line in movement_lines:
                lines.append(f"\t{movement_line}")
            lines.append("")

    GENERATED_JOHTO_ASSETS_PATH.write_text("\n".join(lines).rstrip() + "\n")
    print(f"updated {GENERATED_JOHTO_ASSETS_PATH.relative_to(ROOT)}")


def write_ir_files(manifest):
    IR_DIR.mkdir(parents=True, exist_ok=True)
    ir_index = {}
    for entry in manifest:
        ir = extract_crystal_ir(entry["crystal_map"])
        ir_path = IR_DIR / f"{entry['crystal_map']}.json"
        save_json(ir_path, ir)
        print(f"updated {ir_path.relative_to(ROOT)} from {entry['crystal_map']}")
        ir_index[entry["crystal_map"]] = ir
    return ir_index


def extract_ir_index(manifest):
    return {
        entry["crystal_map"]: extract_crystal_ir(entry["crystal_map"])
        for entry in manifest
    }


def choose_primary_tileset(environment: str) -> str:
    if environment in {"INDOOR", "GATE"}:
        return "gTileset_Building"
    return "gTileset_General"


def choose_map_type(environment: str) -> str:
    return {
        "TOWN": "MAP_TYPE_TOWN",
        "ROUTE": "MAP_TYPE_ROUTE",
        "INDOOR": "MAP_TYPE_INDOOR",
        "GATE": "MAP_TYPE_INDOOR",
        "CAVE": "MAP_TYPE_UNDERGROUND",
        "DUNGEON": "MAP_TYPE_UNDERGROUND",
    }[environment]


def choose_music(ir, entry) -> str:
    if "music" in entry:
        return entry["music"]
    environment = ir["environment"]
    if environment == "ROUTE":
        return "MUS_ROUTE101"
    if environment in {"CAVE", "DUNGEON"}:
        return "MUS_CAVE_OF_ORIGIN"
    return "MUS_LITTLEROOT"


def choose_weather(environment: str) -> str:
    return "WEATHER_SUNNY" if environment in {"TOWN", "ROUTE"} else "WEATHER_NONE"


def placeholder_warp_events(ir):
    return [
        {
            "x": 0,
            "y": 0,
            "elevation": 0,
            "dest_map": "MAP_DYNAMIC",
            "dest_warp_id": "0",
        }
        for _ in ir["events"]["warp_events"]
    ]


def region_section_from_landmark(ir, entry) -> Optional[dict]:
    if entry["region_map_section"] == "MAPSEC_DYNAMIC":
        return None
    landmark = CRYSTAL_LANDMARKS.get(ir["landmark"])
    if landmark is None:
        return None
    return {
        "id": entry["region_map_section"],
        "name": landmark["name"].replace("<BSP>", " "),
        "x": max(0, (landmark["x"] - 20) // 8),
        "y": max(0, (landmark["y"] - 20) // 8),
        "width": 1,
        "height": 1,
    }


def ensure_region_sections(manifest, ir_index):
    data = load_json(REGION_MAP_SECTIONS_PATH)
    sections = data["map_sections"]
    by_id = {section["id"]: section for section in sections}
    changed = False
    referenced_ids = set()

    for entry in manifest:
        section = region_section_from_landmark(ir_index[entry["crystal_map"]], entry)
        if section is None:
            continue
        referenced_ids.add(section["id"])
        if section["id"] in by_id:
            continue
        sections.append(section)
        by_id[section["id"]] = section
        changed = True

    filtered_sections = [
        section for section in sections
        if section["id"] not in PRUNABLE_JOHTO_REGION_SECTIONS or section["id"] in referenced_ids
    ]
    if len(filtered_sections) != len(sections):
        data["map_sections"] = filtered_sections
        changed = True

    if changed:
        save_json(REGION_MAP_SECTIONS_PATH, data)
        print(f"updated {REGION_MAP_SECTIONS_PATH.relative_to(ROOT)}")


def ensure_map_groups(manifest, ir_index):
    data = load_json(MAP_GROUPS_PATH)
    changed = False
    for entry in manifest:
        group_name = entry["target_group"]
        maps = data[group_name]
        if entry["target_name"] not in maps:
            maps.append(entry["target_name"])
            changed = True

    if changed:
        save_json(MAP_GROUPS_PATH, data)
        print(f"updated {MAP_GROUPS_PATH.relative_to(ROOT)}")


def ensure_layouts(manifest, ir_index, crystal_tilesets):
    data = load_json(LAYOUTS_PATH)
    layouts = data["layouts"]
    by_id = {layout["id"]: layout for layout in layouts}
    changed = False

    for entry in manifest:
        ir = ir_index[entry["crystal_map"]]
        tileset = crystal_tilesets[ir["tileset"]]
        layout = by_id.get(entry["layout_id"])
        desired = {
            "id": entry["layout_id"],
            "name": f"{entry['target_name']}_Layout",
            "width": ir["width_blocks"] * 2,
            "height": ir["height_blocks"] * 2,
            "primary_tileset": choose_primary_tileset(ir["environment"]),
            "secondary_tileset": tileset["runtime_tileset"],
            "border_filepath": f"{entry['target_layout_dir']}/border.bin",
            "blockdata_filepath": f"{entry['target_layout_dir']}/map.bin",
        }
        if layout is None:
            layouts.append(desired)
            by_id[entry["layout_id"]] = desired
            changed = True
        elif any(layout.get(key) != value for key, value in desired.items()):
            layout.update(desired)
            changed = True

        layout_dir = ROOT / entry["target_layout_dir"]
        layout_dir.mkdir(parents=True, exist_ok=True)
        for filename in ("map.bin", "border.bin"):
            path = layout_dir / filename
            if not path.exists():
                path.write_bytes(b"")

    if changed:
        save_json(LAYOUTS_PATH, data)
        print(f"updated {LAYOUTS_PATH.relative_to(ROOT)}")


def scaffold_map_json(entry, ir):
    map_path = ROOT / entry["target_map_json"]
    scripts_path = ROOT / entry["target_scripts_path"]
    existed = map_path.exists()
    auto_generated_scripts = not scripts_path.exists() or scripts_path.read_text().startswith(AUTO_SCRIPT_HEADER)
    map_data = load_json(map_path) if existed else {
        "id": entry["map_id"],
        "name": entry["target_name"],
        "layout": entry["layout_id"],
        "music": choose_music(ir, entry),
        "region_map_section": entry["region_map_section"],
        "requires_flash": False,
        "weather": choose_weather(ir["environment"]),
        "map_type": choose_map_type(ir["environment"]),
        "allow_cycling": ir["environment"] in {"TOWN", "ROUTE"},
        "allow_escaping": False,
        "allow_running": ir["environment"] in {"TOWN", "ROUTE"},
        "show_map_name": ir["environment"] in {"TOWN", "ROUTE"},
        "battle_scene": "MAP_BATTLE_SCENE_NORMAL",
        "connections": None,
        "object_events": placeholder_object_events(entry, ir, count=placeholder_object_event_count(entry, ir)) if entry.get("object_mode") in {"exact", "subset", "remap"} else [],
        "warp_events": placeholder_warp_events(ir),
        "coord_events": placeholder_coord_events(entry, ir) if entry.get("coord_mode") in {"exact", "repeat_values"} else [],
        "bg_events": placeholder_bg_events(entry, ir) if entry.get("bg_mode") == "exact" else [],
    }

    map_data["id"] = entry["map_id"]
    map_data["name"] = entry["target_name"]
    map_data["layout"] = entry["layout_id"]
    map_data["region_map_section"] = entry["region_map_section"]
    map_data["map_type"] = choose_map_type(ir["environment"])
    map_data["weather"] = choose_weather(ir["environment"])

    if auto_generated_scripts:
        if entry.get("object_mode") in {"exact", "subset", "remap"}:
            map_data["object_events"] = placeholder_object_events(entry, ir, count=placeholder_object_event_count(entry, ir))
        if entry.get("bg_mode") == "exact":
            map_data["bg_events"] = placeholder_bg_events(entry, ir)
        if entry.get("coord_mode") in {"exact", "repeat_values"}:
            map_data["coord_events"] = placeholder_coord_events(entry, ir)
        if entry.get("warp_mode") == "exact":
            map_data["warp_events"] = placeholder_warp_events(ir)

    if not existed:
        save_json(map_path, map_data)
        print(f"created {map_path.relative_to(ROOT)}")
    elif auto_generated_scripts or (entry.get("warp_mode") == "exact" and "warp_events" not in map_data):
        if entry.get("warp_mode") == "exact":
            map_data["warp_events"] = placeholder_warp_events(ir)
        save_json(map_path, map_data)
        print(f"updated {map_path.relative_to(ROOT)}")


def ensure_scripts_placeholder(entry, ir):
    scripts_path = ROOT / entry["target_scripts_path"]
    if scripts_path.exists() and not scripts_path.read_text().startswith(AUTO_SCRIPT_HEADER):
        return
    scripts_path.parent.mkdir(parents=True, exist_ok=True)
    scripts_path.write_text(build_generated_scripts(entry, ir))
    print(f"updated {scripts_path.relative_to(ROOT)}")


def write_auto_script_includes(manifest):
    event_scripts_path = ROOT / "data" / "event_scripts.s"
    manual_includes = set()
    for raw_line in event_scripts_path.read_text().splitlines():
        marker = '.include "data/maps/'
        if marker not in raw_line:
            continue
        fragment = raw_line.split(marker, 1)[1]
        manual_includes.add(fragment.split("/scripts.inc", 1)[0])

    lines = []
    for entry in manifest:
        if entry["target_name"] in manual_includes:
            continue
        scripts_path = ROOT / entry["target_scripts_path"]
        if not scripts_path.exists():
            continue
        lines.append(f'\t.include "data/maps/{entry["target_name"]}/scripts.inc"')

    AUTO_JOHTO_SCRIPTS_PATH.write_text("\n".join(lines) + ("\n" if lines else ""))
    print(f"updated {AUTO_JOHTO_SCRIPTS_PATH.relative_to(ROOT)}")


def scaffold_targets(manifest, ir_index, crystal_tilesets):
    ensure_region_sections(manifest, ir_index)
    ensure_map_groups(manifest, ir_index)
    ensure_layouts(manifest, ir_index, crystal_tilesets)
    for entry in manifest:
        ir = ir_index[entry["crystal_map"]]
        scaffold_map_json(entry, ir)
        ensure_scripts_placeholder(entry, ir)
    write_auto_script_includes(manifest)


def compile_layout(entry, ir, crystal_tilesets):
    if "target_map_json" not in entry:
        return

    map_data = load_target_map(entry)
    layouts = {layout["id"]: layout for layout in load_json(LAYOUTS_PATH)["layouts"]}
    layout = layouts[map_data["layout"]]
    tileset = crystal_tilesets[ir["tileset"]]
    expected_width = ir["width_blocks"] * 2
    expected_height = ir["height_blocks"] * 2

    if layout["width"] != expected_width or layout["height"] != expected_height:
        raise ValueError(
            f"{entry['id']}: layout {map_data['layout']} dimensions {(layout['width'], layout['height'])} "
            f"do not match exact Crystal size {(expected_width, expected_height)}"
        )
    if layout["secondary_tileset"] != tileset["runtime_tileset"]:
        raise ValueError(
            f"{entry['id']}: layout {map_data['layout']} secondary tileset {layout['secondary_tileset']} "
            f"!= expected {tileset['runtime_tileset']}"
        )

    block_bytes = block_bytes_for_ir(ir)
    expected_block_count = ir["width_blocks"] * ir["height_blocks"]
    if len(block_bytes) != expected_block_count:
        raise ValueError(
            f"{entry['id']}: expected {expected_block_count} blocks in {ir['blk_path']}, found {len(block_bytes)}"
        )

    metatile_rows = []
    for row_index in range(ir["height_blocks"]):
        top_row = []
        bottom_row = []
        for column_index in range(ir["width_blocks"]):
            block_id = block_bytes[row_index * ir["width_blocks"] + column_index]
            translation = tileset["block_translations"].get(block_id)
            if translation is None:
                raise ValueError(
                    f"{entry['id']}: missing translation for {ir['tileset']} block 0x{block_id:02X}"
                )
            tl, tr, bl, br = translation["metatiles"]
            top_row.extend((tl, tr))
            bottom_row.extend((bl, br))
        metatile_rows.append(top_row)
        metatile_rows.append(bottom_row)

    stamp_johto_berry_soil(metatile_rows, map_data)

    border_block_id = int(ir["border_block"], 16)
    border_translation = tileset["block_translations"].get(border_block_id)
    if border_translation is None:
        raise ValueError(
            f"{entry['id']}: missing border translation for {ir['tileset']} block 0x{border_block_id:02X}"
        )

    blockdata_path = ROOT / layout["blockdata_filepath"]
    border_path = ROOT / layout["border_filepath"]
    map_bytes = b"".join(struct.pack("<H", value) for row in metatile_rows for value in row)
    border_bytes = b"".join(struct.pack("<H", value) for value in border_translation["border_metatiles"])

    blockdata_path.write_bytes(map_bytes)
    border_path.write_bytes(border_bytes)
    print(f"updated {blockdata_path.relative_to(ROOT)} from {entry['crystal_map']}")
    print(f"updated {border_path.relative_to(ROOT)} from {entry['crystal_map']}")


def apply_exact_warps(map_data, ir, target_map_index):
    generated = map_data.get("warp_events", [])
    expected = ir["events"]["warp_events"]
    if len(generated) != len(expected):
        raise ValueError(f"{map_data['name']}: warp count {len(generated)} != crystal {len(expected)}")
    unresolved = []
    for index, (event, crystal) in enumerate(zip(generated, expected)):
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]

        if crystal["dest_warp_id"] <= 0:
            event["dest_map"] = "MAP_DYNAMIC"
            event["dest_warp_id"] = "0"
            unresolved.append((index, f"{crystal['dest_map']}#{crystal['dest_warp_id']}"))
            continue

        target = resolve_target_by_crystal_map_id(target_map_index, crystal["dest_map"])
        if target is None:
            target = resolve_target_by_crystal_map(target_map_index, crystal["dest_map"])
        if target is None:
            unresolved.append((index, crystal["dest_map"]))
            continue

        dest_warp_id = crystal["dest_warp_id"] - 1
        if dest_warp_id >= target["warp_count"]:
            raise ValueError(
                f"{map_data['name']}: warp {index} targets {target['map_id']} warp {dest_warp_id}, "
                f"but only {target['warp_count']} warp(s) exist"
            )

        event["dest_map"] = target["map_id"]
        event["dest_warp_id"] = str(dest_warp_id)

    if unresolved:
        fragments = ", ".join(f"{index}:{target}" for index, target in unresolved)
        print(
            f"partially imported warps for {map_data['name']}: unresolved Crystal targets {fragments}",
            file=sys.stderr,
        )


def apply_exact_bg(map_data, ir):
    generated = map_data.get("bg_events", [])
    expected = ir["events"]["bg_events"]
    if len(generated) != len(expected):
        raise ValueError(f"{map_data['name']}: bg count {len(generated)} != crystal {len(expected)}")
    for event, crystal in zip(generated, expected):
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]
        if "player_facing_dir" in event and crystal["kind"] in CRYSTAL_BG_KIND_TO_FACING:
            event["player_facing_dir"] = CRYSTAL_BG_KIND_TO_FACING[crystal["kind"]]


def apply_object_runtime_metadata(event, crystal):
    if crystal["object_type"] != "OBJECTTYPE_TRAINER":
        return
    if event.get("trainer_type") == "TRAINER_TYPE_NONE":
        event["trainer_type"] = "TRAINER_TYPE_NORMAL"
    if "trainer_sight_or_berry_tree_id" in event:
        event["trainer_sight_or_berry_tree_id"] = str(crystal["trainer_sight_range"])


def apply_exact_objects(map_data, ir):
    generated = map_data.get("object_events", [])
    expected = ir["events"]["object_events"]
    if len(generated) != len(expected):
        raise ValueError(f"{map_data['name']}: object count {len(generated)} != crystal {len(expected)}")
    for event, crystal in zip(generated, expected):
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]
        event["movement_range_x"] = crystal["movement_range_x"]
        event["movement_range_y"] = crystal["movement_range_y"]
        apply_object_runtime_metadata(event, crystal)


def apply_subset_objects(entry, map_data, ir):
    generated = map_data.get("object_events", [])
    expected = ir["events"]["object_events"]
    indices = entry["object_indices"]
    if len(generated) != len(indices):
        raise ValueError(f"{map_data['name']}: object count {len(generated)} != subset size {len(indices)}")
    for event, index in zip(generated, indices):
        crystal = expected[index]
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]
        event["movement_range_x"] = crystal["movement_range_x"]
        event["movement_range_y"] = crystal["movement_range_y"]
        apply_object_runtime_metadata(event, crystal)


def apply_remapped_objects(entry, map_data, ir):
    generated = map_data.get("object_events", [])
    expected = ir["events"]["object_events"]
    indices = entry["object_indices"]
    if len(generated) != len(indices):
        raise ValueError(f"{map_data['name']}: object count {len(generated)} != remap size {len(indices)}")
    for event, index in zip(generated, indices):
        crystal = expected[index]
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]
        event["movement_range_x"] = crystal["movement_range_x"]
        event["movement_range_y"] = crystal["movement_range_y"]
        apply_object_runtime_metadata(event, crystal)


def apply_exact_coords(map_data, ir):
    generated = map_data.get("coord_events", [])
    expected = ir["events"]["coord_events"]
    if len(generated) != len(expected):
        raise ValueError(f"{map_data['name']}: coord count {len(generated)} != crystal {len(expected)}")
    for event, crystal in zip(generated, expected):
        event["x"] = crystal["x"]
        event["y"] = crystal["y"]


def apply_repeat_coords(entry, map_data, ir):
    generated = map_data.get("coord_events", [])
    expected = ir["events"]["coord_events"]
    repeat_values = entry["coord_repeat_values"]
    required_count = len(expected) * len(repeat_values)
    if len(generated) != required_count:
        raise ValueError(f"{map_data['name']}: coord count {len(generated)} != repeated crystal count {required_count}")

    cursor = 0
    for crystal in expected:
        for value in repeat_values:
            event = generated[cursor]
            event["x"] = crystal["x"]
            event["y"] = crystal["y"]
            event["var"] = entry["coord_repeat_var"]
            event["var_value"] = value
            cursor += 1


def apply_connections(map_data, ir, target_map_index):
    if not ir["connections"]:
        return

    generated = []
    unresolved = []
    for connection in ir["connections"]:
        target = resolve_target_by_crystal_map(target_map_index, connection["map"])
        if target is None:
            unresolved.append(connection["map"])
            continue
        generated.append(
            {
                "map": target["map_id"],
                "offset": crystal_connection_offset_to_emerald(connection["offset"]),
                "direction": CRYSTAL_TO_EMERALD_DIRECTION[connection["direction"]],
            }
        )

    if unresolved and not generated:
        print(
            f"skipped connection import for {map_data['name']}: unresolved Crystal targets {', '.join(unresolved)}",
            file=sys.stderr,
        )
        return

    if unresolved:
        print(
            f"partially imported connections for {map_data['name']}: unresolved Crystal targets {', '.join(unresolved)}",
            file=sys.stderr,
        )

    map_data["connections"] = generated


def apply_heal_location(entry):
    if "heal_location_id" not in entry or "heal_spawn_local" not in entry:
        return

    heal_data = load_json(HEAL_LOCATIONS_PATH)
    spawn_x, spawn_y = entry["heal_spawn_local"]
    for heal_location in heal_data["heal_locations"]:
        if heal_location["id"] != entry["heal_location_id"]:
            continue
        heal_location["x"] = int(spawn_x)
        heal_location["y"] = int(spawn_y)
        save_json(HEAL_LOCATIONS_PATH, heal_data)
        print(f"updated {HEAL_LOCATIONS_PATH.relative_to(ROOT)} from {entry['crystal_map']}")
        return
    raise ValueError(f"{entry['id']}: heal location '{entry['heal_location_id']}' not found")


def compile_events(entry, ir, target_map_index):
    if "target_map_json" not in entry:
        return

    map_path = ROOT / entry["target_map_json"]
    map_data = load_target_map(entry)

    if entry.get("warp_mode") == "exact":
        apply_exact_warps(map_data, ir, target_map_index)

    if entry.get("bg_mode") == "exact":
        apply_exact_bg(map_data, ir)

    object_mode = entry.get("object_mode")
    if object_mode == "exact":
        apply_exact_objects(map_data, ir)
    elif object_mode == "subset":
        apply_subset_objects(entry, map_data, ir)
    elif object_mode == "remap":
        apply_remapped_objects(entry, map_data, ir)

    coord_mode = entry.get("coord_mode")
    if coord_mode == "exact":
        apply_exact_coords(map_data, ir)
    elif coord_mode == "repeat_values":
        apply_repeat_coords(entry, map_data, ir)

    apply_connections(map_data, ir, target_map_index)
    save_json(map_path, map_data)
    print(f"updated {map_path.relative_to(ROOT)} from {entry['crystal_map']}")
    apply_heal_location(entry)


def run_all(manifest):
    crystal_tilesets = load_crystal_tilesets()
    ir_index = write_ir_files(manifest)
    scaffold_targets(manifest, ir_index, crystal_tilesets)
    write_generated_script_assets(manifest, ir_index)
    target_map_index = load_target_map_index(manifest)

    for entry in manifest:
        compile_layout(entry, ir_index[entry["crystal_map"]], crystal_tilesets)
    for entry in manifest:
        compile_events(entry, ir_index[entry["crystal_map"]], target_map_index)


def run_extract(manifest):
    write_ir_files(manifest)


def run_scaffold(manifest):
    crystal_tilesets = load_crystal_tilesets()
    ir_index = extract_ir_index(manifest)
    scaffold_targets(manifest, ir_index, crystal_tilesets)


def run_compile_layouts(manifest):
    crystal_tilesets = load_crystal_tilesets()
    ir_index = extract_ir_index(manifest)
    scaffold_targets(manifest, ir_index, crystal_tilesets)
    for entry in manifest:
        compile_layout(entry, ir_index[entry["crystal_map"]], crystal_tilesets)


def run_compile_events(manifest):
    ir_index = extract_ir_index(manifest)
    scaffold_targets(manifest, ir_index, load_crystal_tilesets())
    write_generated_script_assets(manifest, ir_index)
    target_map_index = load_target_map_index(manifest)
    for entry in manifest:
        compile_events(entry, ir_index[entry["crystal_map"]], target_map_index)


def run_compile_script_assets(manifest):
    ir_index = extract_ir_index(manifest)
    write_generated_script_assets(manifest, ir_index)


def parse_args():
    parser = argparse.ArgumentParser(description="Import Crystal-authored Johto maps into pokeemerald.")
    parser.add_argument(
        "stage",
        nargs="?",
        default="all",
        choices=("all", "extract", "scaffold", "compile-layouts", "compile-events", "compile-script-assets"),
        help="Importer stage to run. Default: all",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    manifest = load_import_manifest()

    if args.stage == "all":
        run_all(manifest)
    elif args.stage == "extract":
        run_extract(manifest)
    elif args.stage == "scaffold":
        run_scaffold(manifest)
    elif args.stage == "compile-layouts":
        run_compile_layouts(manifest)
    elif args.stage == "compile-events":
        run_compile_events(manifest)
    elif args.stage == "compile-script-assets":
        run_compile_script_assets(manifest)
    else:
        raise AssertionError(f"unhandled stage {args.stage}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
